// PER-ELEMENT LAYERS ON A BUILT-IN TEMPLATE
//
// A template is one drawn design: a root that paints the background and a flat
// list of absolutely-positioned children sitting on it. That shape is what
// makes this possible without recreating any layout — each root child is
// already a discrete visual element, so it only needs an addressable z-index
// and a name to become a layer.
//
// The alternative was `templateToBlocks`, which recreates a layout as freeform
// blocks. It reaches four templates and each entry is hand-placed x/y/fontSize,
// so extending it to 48 would mean redrawing every layout AND throwing away the
// per-layout AutoFitText sizing, the responsive squad logic and the portrait
// designs. Nothing here touches any of that: the template still renders itself,
// it just does so through a root that knows what its own children are.
//
// WITHOUT A PROVIDER — and with a provider that has nothing to apply — a
// LayerRoot renders the exact div the template used to render. That is the
// guarantee that makes this safe to put under all 48: a post nobody has
// reordered goes through the same code path it always did.
import { createContext, useContext, useEffect, useMemo, Children, cloneElement, isValidElement } from 'react'

const PostLayerContext = createContext(null)

export const BLOCK_RUN = 'blocks'

export function PostLayerProvider({ value, children }) {
  return <PostLayerContext.Provider value={value}>{children}</PostLayerContext.Provider>
}

// ─────────────────────────────────────────────────────────────────────────────
// DESCRIBING A ROOT CHILD
// ─────────────────────────────────────────────────────────────────────────────

// The first run of real text inside an element, for naming a layer after what
// it says. Depth-first so a heading nested in a wrapper still names its layer,
// and capped because a squad list would otherwise name itself after all 13.
function firstText(node, depth = 0) {
  if (depth > 6) return ''
  if (node == null || node === false || node === true) return ''
  if (typeof node === 'string') return node.trim()
  if (typeof node === 'number') return String(node)
  if (Array.isArray(node)) {
    for (const n of node) { const t = firstText(n, depth + 1); if (t) return t }
    return ''
  }
  if (isValidElement(node)) {
    // A template's own text often arrives as a prop rather than a child
    // (AutoFitText takes `text`), so those are read before the subtree.
    for (const k of ['text', 'label', 'title']) {
      const v = node.props?.[k]
      if (typeof v === 'string' && v.trim()) return v.trim()
    }
    return firstText(node.props?.children, depth + 1)
  }
  return ''
}

function typeName(node) {
  const t = node?.type
  if (typeof t === 'string') return t
  return t?.displayName || t?.name || 'Element'
}

// The shared primitives every family draws with, named the way somebody
// looking at the post would name them. One map covers all 48 templates, which
// is why these never needed a `data-layer` of their own.
const FRIENDLY = {
  Halftone: 'Halftone texture',
  Stripes: 'Stripe texture',
  Grain: 'Grain',
  GrainSVG: 'Grain',
  SponsorFooter: 'Sponsors',
  Watermark: 'Sponsor watermark',
  BrandLockup: 'Club lockup',
  ClubLockup: 'Club lockup',
  ClubLogo: 'Club crest',
  Monogram: 'Club monogram',
  Shield: 'Club shield',
  CreditMark: 'BetterCricket credit',
  PhotoLayer: 'Photo',
  AutoFitText: 'Headline',
  AutoFit: 'Headline',
  NavStrip: 'Nav strip',
  Panel: 'Panel',
}

// The first component inside an element that has a name worth showing — for a
// wrapper whose whole content is generated by a child (a div holding nothing
// but <SponsorFooter/>), which has no text of its own to be named after.
function firstKnown(node, depth = 0) {
  if (depth > 6 || node == null || typeof node !== 'object') return ''
  if (Array.isArray(node)) {
    for (const n of node) { const f = firstKnown(n, depth + 1); if (f) return f }
    return ''
  }
  if (!isValidElement(node)) return ''
  const named = FRIENDLY[typeName(node)]
  if (named) return named
  return firstKnown(node.props?.children, depth + 1)
}

// A label a person can pick out of a list. An explicit `data-layer` always
// wins; then a known primitive's own name; then the element's own words, which
// for these templates reads well ("FULL TIME", "MATCH DAY", "★ POTM").
function labelFor(node, idx) {
  const explicit = node.props?.['data-layer']
  if (explicit) return String(explicit)
  const named = FRIENDLY[typeName(node)]
  if (named) return named
  const text = firstText(node)
  if (text) return text.length > 26 ? text.slice(0, 25).trimEnd() + '…' : text
  const inner = firstKnown(node.props?.children)
  if (inner) return inner
  const t = typeName(node)
  return t === 'div' ? `Element ${idx + 1}` : t
}

// IDENTITY IS STRUCTURAL, NEVER THE TEXT. A layer named after its own words
// would lose its place in the stack the moment somebody edited those words, so
// the id is the element's type plus which one of that type it is. An explicit
// `data-layer` overrides it, which is what a conditionally-rendered child needs
// — its structural position shifts as it appears and disappears.
function idsFor(nodes) {
  const seen = new Map()
  return nodes.map((node) => {
    const explicit = node.props?.['data-layer']
    if (explicit) return `n:${explicit}`
    const t = typeName(node)
    const n = seen.get(t) || 0
    seen.set(t, n + 1)
    return `t:${t}#${n}`
  })
}

// ─────────────────────────────────────────────────────────────────────────────
// NATURAL ORDER
// ─────────────────────────────────────────────────────────────────────────────

// What the template paints today, as an explicit list. DOM order, except where
// a child already carries its own z-index — T1's match-day badge sits at 5 and
// has to keep painting over the hero photo that follows it in the markup.
// Sorted stably so equal z-indexes stay in markup order.
function naturalOrder(nodes) {
  return nodes
    .map((node, i) => ({ i, z: Number(node.props?.style?.zIndex) || 0 }))
    .sort((a, b) => (a.z - b.z) || (a.i - b.i))
    .map((e) => e.i)
}

// A preference layered over the natural order rather than a replacement for it:
// ids the caller knows about are taken in its order, and anything it has never
// heard of (a template's own new element, a block just added) drops back into
// the place it would naturally have had. Same call `sort_order` makes elsewhere
// — the stored order is what somebody chose, not the whole truth.
export function applyOrder(naturalIds, order) {
  if (!order || !order.length) return naturalIds
  const natural = new Set(naturalIds)
  const kept = order.filter((id) => natural.has(id))
  if (kept.length === naturalIds.length) return kept
  const placed = new Set(kept)
  const out = kept.slice()
  naturalIds.forEach((id, idx) => {
    if (placed.has(id)) return
    // Back in at its own index, which is where it sat before anybody had an
    // opinion about it.
    out.splice(Math.min(idx, out.length), 0, id)
  })
  return out
}

// ─────────────────────────────────────────────────────────────────────────────
// THE ROOT
// ─────────────────────────────────────────────────────────────────────────────

export function LayerRoot({ style, children, ...rest }) {
  const ctx = useContext(PostLayerContext)

  // Children.toArray drops null/false, so a conditional element that is not
  // rendered is simply not a layer — which is the right answer, and the reason
  // one that comes and goes wants an explicit `data-layer` name.
  const nodes = useMemo(
    () => Children.toArray(children).filter(isValidElement),
    [children],
  )
  const ids = useMemo(() => idsFor(nodes), [nodes])
  const natural = useMemo(() => naturalOrder(nodes), [nodes])
  const naturalIds = useMemo(() => natural.map((i) => ids[i]), [natural, ids])

  // Report the stack to whoever is drawing the Layers panel. Keyed on the ids
  // and labels rather than the nodes, or every content change would re-register
  // and the panel would churn on each keystroke.
  const register = ctx?.register
  const descriptors = useMemo(
    () => natural.map((i) => ({ id: ids[i], label: labelFor(nodes[i], i) })),
    [natural, ids, nodes],
  )
  const signature = descriptors.map((d) => d.id + ' ' + d.label).join('')
  useEffect(() => {
    if (!register) return
    register(descriptors)
  }, [register, signature]) // eslint-disable-line react-hooks/exhaustive-deps

  const blocks = ctx?.blocks
  const hidden = ctx?.hidden
  const order = ctx?.order
  const nothingToApply = !ctx
    || (!order?.length && !hidden?.size && !blocks?.length)

  // THE UNTOUCHED PATH. Byte-for-byte the div every template rendered before
  // any of this existed — no cloning, no z-index, no stacking context — so a
  // post nobody has reordered cannot have moved.
  if (nothingToApply) return <div style={style} {...rest}>{children}</div>

  const blockById = new Map((blocks || []).map((b) => [b.id, b]))
  // Blocks start in front of the whole layout, which is where an added block
  // has always landed.
  const allNatural = [...naturalIds, ...(blocks || []).map((b) => b.id)]
  const ordered = applyOrder(allNatural, order)

  const byId = new Map(ids.map((id, i) => [id, nodes[i]]))
  const out = []
  let run = []
  let z = 0
  const flushRun = () => {
    if (!run.length) return
    const items = run
    run = []
    z += 1
    out.push(ctx.renderRun(items, `run-${out.length}`, z))
  }
  ordered.forEach((id) => {
    const block = blockById.get(id)
    if (block) { run.push(block); return }
    const node = byId.get(id)
    if (!node) return
    flushRun()
    if (hidden?.has(id)) return
    z += 1
    out.push(cloneElement(node, {
      key: id,
      style: { ...(node.props?.style || {}), zIndex: z },
      // Only a plain DOM child can carry it — a component would take it as an
      // unknown prop and drop it. Enough to name what is where in the stack,
      // which is what a check measuring "between these two" needs.
      ...(typeof node.type === 'string' ? { 'data-layer-id': id } : null),
    }))
  })
  flushRun()

  // `isolation` makes the root its own stacking context, so its background is
  // the floor every layer sits on and no z-index here can escape into the
  // canvas around it. That is exactly the promise being made: everything except
  // the background is a layer.
  return <div style={{ ...style, isolation: 'isolate' }} {...rest}>{out}</div>
}

export default LayerRoot
