"""Usage breadcrumbs — endpoints.

- POST /usage/event: public beacon for frontend SPA route changes.
  Marketing pages, public yearbooks, in-app routes — everything the
  user sees that doesn't naturally hit its own API.
- GET /club-admin/usage/recent: super-admin only — latest events.
- GET /club-admin/usage/summary: top-level counters for the window.
- GET /club-admin/usage/timeseries: hits per bucket for the window.
- GET /club-admin/usage/top-routes: aggregated route counts.
- GET /club-admin/usage/top-users: most active users.
- GET /club-admin/usage/by-feature: rolled-up feature buckets
  (Players, Yearbooks, Marketing, etc.) — coarser than top-routes.
- GET /club-admin/usage/by-role: events split by user role.

API-call events come from the middleware in app.main; the beacon writes
the page-view events.

All admin views accept a `role` query param that filters to events
generated by users of that role (super_admin / club_admin / club_member
/ anon for logged-out hits).
"""
from __future__ import annotations

import re
import uuid as _uuid
from datetime import datetime, timezone
from typing import Optional
from urllib.parse import unquote_plus

from fastapi import APIRouter, Depends, Query, Request
from pydantic import BaseModel
from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.db import User, get_db
from app.routers.auth import require_super_admin
from app.services import platform_settings as ps
from app.services.club_directory import _resolved_cid_sql
from app.services.usage_tracker import record_event

router = APIRouter(tags=["usage"])

_UUID_RE = re.compile(
    r"[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}",
    re.IGNORECASE,
)


# Highest-priority role wins when a user has multiple memberships.
# Anonymous events (no user_id) bucket as 'anon'.
ALLOWED_ROLES = ("super_admin", "club_admin", "club_member", "anon")

# Subquery that resolves a user to their single highest-priority role.
# LATERAL so it picks one row per user; ordered super > admin > member.
_USER_ROLE_JOIN = """
LEFT JOIN LATERAL (
    SELECT role, club_id
    FROM club_memberships
    WHERE user_id = ue.user_id
    ORDER BY CASE role
        WHEN 'super_admin'  THEN 0
        WHEN 'club_admin'   THEN 1
        WHEN 'club_member'  THEN 2
        ELSE 3
    END
    LIMIT 1
) cm ON ue.user_id IS NOT NULL
"""


def _normalise_roles(roles: Optional[list[str]]) -> list[str]:
    """Validate + dedupe an incoming list of role filter values.

    Accepts either a real list (FastAPI multi-`?role=` form) or a single
    comma-separated string for convenience.
    """
    if not roles:
        return []
    out: list[str] = []
    for r in roles:
        if r is None:
            continue
        for part in str(r).split(","):
            part = part.strip()
            if part in ALLOWED_ROLES and part not in out:
                out.append(part)
    return out


def _role_filter(roles: list[str]) -> str:
    """SQL fragment to AND into the WHERE clause for a multi-role filter.

    Empty string when no role filter. When `anon` is in the list it OR's
    a `user_id IS NULL` branch with the named-role IN (...) branch.
    """
    if not roles:
        return ""
    named = [r for r in roles if r != "anon"]
    include_anon = "anon" in roles
    if named and include_anon:
        return "AND (cm.role = ANY(:role_filter) OR ue.user_id IS NULL)"
    if named:
        return "AND cm.role = ANY(:role_filter)"
    # anon only
    return "AND ue.user_id IS NULL"


def _role_params(roles: list[str]) -> dict:
    named = [r for r in roles if r != "anon"]
    if named:
        return {"role_filter": named}
    return {}


def _search_clause(q: Optional[str], params: dict) -> str:
    """ANDable clause matching a free-text query against the path, route and
    UTM fields. Mutates ``params`` to add the ``:q`` bind.

    The page-view beacon stores the FULL landing URL (incl. the query string)
    in ``path``, so a search like ``utm_campaign=spring`` or ``applecross``
    matches historical rows too — not just the rows written after the dedicated
    utm_* columns existed. Empty/whitespace ``q`` → no clause.

    A bare UUID (e.g. pasted from an onboarding request's visitor id, or a
    deep link from SuperOnboarding's "View activity" button) matches
    ``visitor_id`` exactly instead — that's how a lead's own enquiry links
    back to the page-view journey that led to it."""
    if not q or not q.strip():
        return ""
    trimmed = q.strip()
    if _UUID_RE.fullmatch(trimmed):
        params["q"] = trimmed
        return "AND ue.visitor_id::text = :q"
    params["q"] = f"%{trimmed}%"
    return (
        "AND (ue.path ILIKE :q OR ue.route ILIKE :q "
        "OR ue.utm_source ILIKE :q OR ue.utm_campaign ILIKE :q "
        "OR ue.utm_content ILIKE :q OR ue.utm_medium ILIKE :q)"
    )


# ─── Visitor identity ────────────────────────────────────────────────────────
# A visitor is keyed by the first-party `visitor_id` (a random UUID the SPA
# keeps in localStorage) when present, falling back to the hashed IP for legacy
# rows written before visitor_id existed. This single expression is reused
# across the visitor/lead views so "returning" is computed the same way
# everywhere — and survives an IP change, which the hash alone could not.
_VKEY = "COALESCE(ue.visitor_id::text, ue.ip_hash)"

# Page paths that signal buying intent — a visit here is a warm lead.
_INTENT_CONTACT = "split_part(ue.path, '?', 1) ~* '^/contact(/|$)'"
_INTENT_PRICING = "split_part(ue.path, '?', 1) ~* '^/pricing(/|$)'"


def _parse_device(ua: Optional[str]) -> dict:
    """Coarse device read from the user-agent. Good enough to tell a phone
    from a laptop and name the browser — we don't ship a full UA database."""
    s = ua or ""
    low = s.lower()
    if not s:
        dtype = "unknown"
    elif any(b in low for b in (
        "bot", "crawl", "spider", "slurp", "bingpreview",
        "facebookexternalhit", "headless", "lighthouse", "preview",
    )):
        dtype = "bot"
    elif "ipad" in low or "tablet" in low or ("android" in low and "mobile" not in low):
        dtype = "tablet"
    elif any(b in low for b in ("mobi", "iphone", "ipod", "android")):
        dtype = "mobile"
    else:
        dtype = "desktop"

    if any(b in low for b in ("iphone", "ipad", "ipod")) or "cpu os" in low:
        os_ = "iOS"
    elif "android" in low:
        os_ = "Android"
    elif "windows" in low:
        os_ = "Windows"
    elif "mac os" in low or "macintosh" in low:
        os_ = "macOS"
    elif "cros" in low:
        os_ = "ChromeOS"
    elif "linux" in low:
        os_ = "Linux"
    else:
        os_ = None

    if "edg" in low:
        br = "Edge"
    elif "opr" in low or "opera" in low:
        br = "Opera"
    elif "samsungbrowser" in low:
        br = "Samsung"
    elif "crios" in low or "chrome" in low:
        br = "Chrome"
    elif "fxios" in low or "firefox" in low:
        br = "Firefox"
    elif "safari" in low:
        br = "Safari"
    else:
        br = None
    return {"type": dtype, "os": os_, "browser": br}


def _src_sql(a: str) -> str:
    """Read-time traffic source as a SQL expression for table alias ``a``.

    The page-view beacon has always stored the FULL landing URL (incl. the
    query string) in ``path``, so UTMs and ad-click ids live there for every
    event ever recorded — no backfill needed. We prefer the bucketed
    ``traffic_source`` column when present (new first-touch attribution), else
    parse the query string, else fall back to the referring host."""
    return f"""COALESCE(
      NULLIF({a}.traffic_source, ''),
      CASE
        WHEN {a}.path ~* 'utm_source=' THEN
          CASE lower(substring({a}.path from 'utm_source=([^&]+)'))
            WHEN 'fb' THEN 'facebook' WHEN 'facebook' THEN 'facebook'
            WHEN 'meta' THEN 'facebook' WHEN 'messenger' THEN 'facebook'
            WHEN 'ig' THEN 'instagram' WHEN 'instagram' THEN 'instagram'
            WHEN 'google' THEN 'google' WHEN 'adwords' THEN 'google'
            WHEN 'newsletter' THEN 'email' WHEN 'email' THEN 'email'
            ELSE lower(substring({a}.path from 'utm_source=([^&]+)'))
          END
        WHEN {a}.path ~* 'fbclid=' THEN 'facebook'
        WHEN {a}.path ~* '(gclid|gbraid|wbraid)=' THEN 'google'
        WHEN {a}.path ~* 'msclkid=' THEN 'bing'
        WHEN {a}.path ~* 'ttclid=' THEN 'tiktok'
        WHEN {a}.path ~* 'igshid=' THEN 'instagram'
        WHEN {a}.referer ~* '(facebook\\.|fb\\.me|l\\.facebook|lm\\.facebook)' THEN 'facebook'
        WHEN {a}.referer ~* 'instagram\\.' THEN 'instagram'
        WHEN {a}.referer ~* 'google\\.' THEN 'google'
        WHEN {a}.referer ~* 'bing\\.' THEN 'bing'
        WHEN {a}.referer ~* '(t\\.co|twitter\\.|x\\.com)' THEN 'twitter'
        WHEN {a}.referer ~* '(linkedin\\.|lnkd\\.in)' THEN 'linkedin'
        WHEN {a}.referer IS NOT NULL
             AND {a}.referer !~* '(betterat\\.cricket|betterstats\\.cricket|localhost|127\\.0\\.0\\.1)'
          THEN 'referral'
        ELSE 'direct'
      END)"""


_RESERVED_PAGES = {
    "pricing": "Pricing", "contact": "Contact", "features": "Features",
    "about": "About", "faq": "FAQ", "terms": "Terms", "privacy": "Privacy",
    "login": "Login", "fantasy": "Fantasy",
}
_CLUB_SECTIONS = {
    "yearbook": "Yearbook", "leaderboard": "Leaderboard", "records": "Records",
    "statlab": "StatLab", "compare": "Compare", "players": "Players",
    "teams": "Teams", "awards": "Awards",
}


def _page_label(path: Optional[str]) -> str:
    """A short human label for a page path, for the live feed."""
    p = (path or "/").split("?")[0].rstrip("/")
    if not p:
        return "Home"
    seg = [s for s in p.split("/") if s]
    if not seg:
        return "Home"
    first = seg[0].lower()
    if first in _RESERVED_PAGES:
        return _RESERVED_PAGES[first]
    if first == "blog":
        return "Blog" if len(seg) == 1 else "Blog: " + seg[1].replace("-", " ").title()
    if first == "players":
        return "Player profile"
    if first in ("games", "match", "scorecards"):
        return "Match scorecard"
    if first == "admin":
        return "Admin"
    label = seg[0].replace("-", " ").title()
    if len(seg) == 1:
        return f"{label} (club)"
    section = seg[1].lower()
    if section in _CLUB_SECTIONS:
        return f"{label}: {_CLUB_SECTIONS[section]}"
    return label


# ─── Feature categorisation (Python-side, after group-by route) ──────────────

def _categorise(route: Optional[str], path: Optional[str], event_type: str) -> str:
    s = (route or path or "").lower()
    if not s:
        return "Other"
    if event_type == "page_view":
        if s in ("/", "/features", "/pricing", "/about", "/contact",
                 "/faq", "/terms", "/privacy"):
            return "Marketing"
        if s.startswith("/blog"):
            return "Marketing — Blog"
        if s.startswith("/login"):
            return "Auth pages"
        if s.startswith("/admin"):
            return "Admin pages"
        if s.startswith("/players/"):
            return "Player profiles"
        if (s.startswith("/games/") or s.startswith("/match/")
                or s.startswith("/scorecards/")):
            return "Match pages"
        if "/yearbook" in s:
            return "Yearbooks"
        if "/leaderboard" in s:
            return "Leaderboard"
        if "/statlab" in s:
            return "StatLab"
        if "/records" in s:
            return "Records"
        if "/compare" in s:
            return "Player comparison"
        if "/dashboard" in s:
            return "Club dashboard"
        # Canonical club home: /:clubSlug (no second segment). The leading
        # slash gives one empty + one non-empty segment; reserved roots are
        # handled by earlier branches.
        parts = [p for p in s.split("?")[0].split("/") if p]
        if len(parts) == 1:
            return "Club dashboard"
        return "Other pages"
    # API
    if s.startswith("/auth"):
        return "Auth"
    if "/yearbook" in s:
        return "Yearbooks"
    if "/club-admin/players" in s or s.startswith("/players"):
        return "Players"
    if s.startswith("/games") or s.startswith("/scorecards"):
        return "Matches"
    if "/leaderboard" in s:
        return "Leaderboard"
    if "/statlab" in s:
        return "StatLab"
    if "/records" in s:
        return "Records"
    if "/sync" in s or "hard-refresh" in s:
        return "Sync / Refresh"
    if s.startswith("/club-admin"):
        return "Admin actions"
    if s.startswith("/organisations"):
        return "Organisations"
    if s.startswith("/usage"):
        return "Usage tracking"
    return "Other API"


# ─── Public beacon ───────────────────────────────────────────────────────────

class PageViewIn(BaseModel):
    path: str
    referer: Optional[str] = None
    name: Optional[str] = None
    # Lead-tracking: a stable first-party visitor id + first-touch acquisition,
    # all supplied by the SPA beacon (see frontend lib/visitor.js).
    visitor_id: Optional[str] = None
    utm_source: Optional[str] = None
    utm_medium: Optional[str] = None
    utm_campaign: Optional[str] = None
    utm_content: Optional[str] = None
    utm_id: Optional[str] = None
    click_id: Optional[str] = None
    click_source: Optional[str] = None
    landing_referrer: Optional[str] = None
    landing_path: Optional[str] = None


class HeartbeatIn(BaseModel):
    path: str
    visitor_id: Optional[str] = None


@router.post("/usage/heartbeat")
async def post_heartbeat(payload: HeartbeatIn, request: Request):
    """A lightweight "still here" ping the SPA sends every ~25s while a public
    page is open and the tab is visible (see frontend hooks/useHeartbeat.js).
    Lets the Usage page's "Active now" reflect someone actually having the
    page open right now, rather than inferring presence from how recently
    their last page_view landed."""
    from app.main import _decode_user_id, _client_ip, _cf_country  # avoid import cycle

    await record_event(
        event_type="heartbeat",
        method="GET",
        path=payload.path or "/",
        status=200,
        user_id=_decode_user_id(request),
        ip=_client_ip(request),
        user_agent=request.headers.get("user-agent"),
        country=_cf_country(request),
        visitor_id=payload.visitor_id,
    )
    return {"ok": True}


@router.post("/usage/event")
async def post_event(payload: PageViewIn, request: Request):
    """Anonymous SPA page-view beacon."""
    from app.main import _decode_user_id, _client_ip, _cf_country  # avoid import cycle

    await record_event(
        event_type="page_view",
        method="GET",
        path=payload.path or "/",
        route=payload.name,
        status=200,
        user_id=_decode_user_id(request),
        ip=_client_ip(request),
        user_agent=request.headers.get("user-agent"),
        referer=payload.referer or request.headers.get("referer"),
        country=_cf_country(request),
        visitor_id=payload.visitor_id,
        utm_source=payload.utm_source,
        utm_medium=payload.utm_medium,
        utm_campaign=payload.utm_campaign,
        utm_content=payload.utm_content,
        utm_id=payload.utm_id,
        click_id=payload.click_id,
        click_source=payload.click_source,
        landing_referrer=payload.landing_referrer,
        landing_path=payload.landing_path,
    )
    return {"ok": True}


class PageExitIn(BaseModel):
    path: str
    time_on_page_ms: int
    visitor_id: Optional[str] = None


@router.post("/usage/event/exit")
async def post_event_exit(payload: PageExitIn, request: Request):
    """Anonymous SPA dwell-time beacon — how long the visitor was actually on
    ``path`` before navigating away, backgrounding the tab, or closing it.
    Fired by usePageView.js on visibilitychange/pagehide, not on every page
    view (there's no meaningful dwell time until the visitor leaves).

    Written as its own event_type ('page_exit') rather than an UPDATE of the
    original page_view row: sendBeacon calls on unload can't reliably read
    back the original row's id, and an append-only insert is exactly the
    pattern the rest of this table already uses. Read-time joins (session
    duration, per-page average dwell) match a page_exit to its page_view by
    (visitor_id, path, nearest following timestamp) — see
    services/usage.py / the /usage/session-duration and /usage/journey routes."""
    from app.main import _decode_user_id, _client_ip, _cf_country  # avoid import cycle

    await record_event(
        event_type="page_exit",
        method="GET",
        path=payload.path or "/",
        status=200,
        user_id=_decode_user_id(request),
        ip=_client_ip(request),
        user_agent=request.headers.get("user-agent"),
        country=_cf_country(request),
        visitor_id=payload.visitor_id,
        time_on_page_ms=payload.time_on_page_ms,
    )
    return {"ok": True}


# ─── Super-admin views ───────────────────────────────────────────────────────

@router.get("/club-admin/usage/summary")
async def summary(
    days: int = 7,
    role: Optional[list[str]] = Query(None),
    event_type: Optional[str] = None,
    q: Optional[str] = None,
    _: User = Depends(require_super_admin),
    db: AsyncSession = Depends(get_db),
):
    days = max(1, min(days, 365))
    roles = _normalise_roles(role)
    params: dict = {"days": days, **_role_params(roles)}
    extra = []
    if event_type:
        extra.append("AND ue.event_type = :etype")
        params["etype"] = event_type
    extras = "\n".join(extra) + " " + _role_filter(roles) + " " + _search_clause(q, params)
    row = await db.execute(
        text(
            f"""
            SELECT
                COUNT(*)                                                            AS total,
                COUNT(*) FILTER (WHERE ue.event_type = 'api')                       AS api_hits,
                COUNT(*) FILTER (WHERE ue.event_type = 'page_view')                 AS page_views,
                COUNT(DISTINCT ue.user_id) FILTER (WHERE ue.user_id IS NOT NULL)    AS unique_users,
                COUNT(DISTINCT ue.ip_hash) FILTER (WHERE ue.ip_hash IS NOT NULL)    AS unique_ips
            FROM usage_events ue
            {_USER_ROLE_JOIN}
            WHERE ue.created_at >= NOW() - (:days * INTERVAL '1 day')
            {extras}
            """
        ),
        params,
    )
    r = row.mappings().first()
    return {
        "days": days,
        "total": int(r["total"] or 0),
        "api_hits": int(r["api_hits"] or 0),
        "page_views": int(r["page_views"] or 0),
        "unique_users": int(r["unique_users"] or 0),
        "unique_ips": int(r["unique_ips"] or 0),
    }


@router.get("/club-admin/usage/timeseries")
async def timeseries(
    days: int = 7,
    role: Optional[list[str]] = Query(None),
    event_type: Optional[str] = None,
    q: Optional[str] = None,
    _: User = Depends(require_super_admin),
    db: AsyncSession = Depends(get_db),
):
    """Hits per bucket. Bucket = hour for 24h window, day for >24h."""
    days = max(1, min(days, 365))
    bucket = "hour" if days <= 1 else "day"
    roles = _normalise_roles(role)
    params: dict = {"days": days, **_role_params(roles)}
    type_clause = ""
    if event_type:
        type_clause = "AND ue.event_type = :etype"
        params["etype"] = event_type
    search = _search_clause(q, params)
    rows = await db.execute(
        text(
            f"""
            SELECT
                date_trunc('{bucket}', ue.created_at) AS bucket,
                COUNT(*) FILTER (WHERE ue.event_type = 'api')        AS api_hits,
                COUNT(*) FILTER (WHERE ue.event_type = 'page_view')  AS page_views,
                COUNT(*) AS total
            FROM usage_events ue
            {_USER_ROLE_JOIN}
            WHERE ue.created_at >= NOW() - (:days * INTERVAL '1 day')
            {type_clause}
            {_role_filter(roles)}
            {search}
            GROUP BY bucket
            ORDER BY bucket ASC
            """
        ),
        params,
    )
    return {
        "bucket": bucket,
        "points": [
            {
                "bucket": r["bucket"].isoformat() if r["bucket"] else None,
                "api_hits": int(r["api_hits"] or 0),
                "page_views": int(r["page_views"] or 0),
                "total": int(r["total"] or 0),
            }
            for r in rows.mappings().all()
        ],
    }


@router.get("/club-admin/usage/by-feature")
async def by_feature(
    days: int = 7,
    role: Optional[list[str]] = Query(None),
    event_type: Optional[str] = None,
    q: Optional[str] = None,
    _: User = Depends(require_super_admin),
    db: AsyncSession = Depends(get_db),
):
    """Group routes/paths into feature buckets. Bucketing is Python-side
    so the SQL stays readable; the data volume per window is small."""
    days = max(1, min(days, 365))
    roles = _normalise_roles(role)
    params: dict = {"days": days, **_role_params(roles)}
    type_clause = ""
    if event_type:
        type_clause = "AND ue.event_type = :etype"
        params["etype"] = event_type
    search = _search_clause(q, params)
    rows = await db.execute(
        text(
            f"""
            SELECT
                ue.route,
                ue.path,
                ue.event_type,
                COUNT(*) AS hits
            FROM usage_events ue
            {_USER_ROLE_JOIN}
            WHERE ue.created_at >= NOW() - (:days * INTERVAL '1 day')
            {type_clause}
            {_role_filter(roles)}
            {search}
            GROUP BY ue.route, ue.path, ue.event_type
            """
        ),
        params,
    )
    buckets: dict[str, int] = {}
    for r in rows.mappings().all():
        feat = _categorise(r["route"], r["path"], r["event_type"])
        buckets[feat] = buckets.get(feat, 0) + int(r["hits"] or 0)
    return sorted(
        [{"feature": k, "hits": v} for k, v in buckets.items()],
        key=lambda x: x["hits"],
        reverse=True,
    )


@router.get("/club-admin/usage/by-role")
async def by_role(
    days: int = 7,
    event_type: Optional[str] = None,
    _: User = Depends(require_super_admin),
    db: AsyncSession = Depends(get_db),
):
    """Hit count grouped by the user's role (incl. anon)."""
    days = max(1, min(days, 365))
    params: dict = {"days": days}
    type_clause = ""
    if event_type:
        type_clause = "AND ue.event_type = :etype"
        params["etype"] = event_type
    rows = await db.execute(
        text(
            f"""
            SELECT
                COALESCE(cm.role, 'anon') AS role,
                COUNT(*) AS hits,
                COUNT(DISTINCT ue.user_id) FILTER (WHERE ue.user_id IS NOT NULL) AS unique_users
            FROM usage_events ue
            {_USER_ROLE_JOIN}
            WHERE ue.created_at >= NOW() - (:days * INTERVAL '1 day')
            {type_clause}
            GROUP BY COALESCE(cm.role, 'anon')
            ORDER BY hits DESC
            """
        ),
        params,
    )
    return [
        {
            "role": r["role"],
            "hits": int(r["hits"] or 0),
            "unique_users": int(r["unique_users"] or 0),
        }
        for r in rows.mappings().all()
    ]


@router.get("/club-admin/usage/by-club")
async def by_club(
    days: int = 7,
    role: Optional[list[str]] = Query(None),
    event_type: Optional[str] = None,
    q: Optional[str] = None,
    _: User = Depends(require_super_admin),
    db: AsyncSession = Depends(get_db),
):
    """Usage attributed to each club.

    Two attribution paths, both query-time (so it works on existing data, no
    backfill): an event's explicit ``org_id`` when set, else — for public SPA
    page views — the club slug parsed out of the path (``/{slug}/…``). Events
    that resolve to neither (marketing pages, admin pages, API calls with no
    org context) are bucketed as ``Unattributed`` so the totals reconcile.
    """
    days = max(1, min(days, 365))
    roles = _normalise_roles(role)
    params: dict = {"days": days, **_role_params(roles)}
    type_clause = ""
    if event_type:
        type_clause = "AND ue.event_type = :etype"
        params["etype"] = event_type
    search = _search_clause(q, params)
    rows = await db.execute(
        text(
            f"""
            SELECT
                COALESCE(o_org.id::text, o_slug.id::text)       AS club_id,
                COALESCE(o_org.name, o_slug.name)               AS club_name,
                COALESCE(o_org.slug, o_slug.slug)               AS club_slug,
                COUNT(*)                                        AS hits,
                COUNT(*) FILTER (WHERE ue.event_type = 'page_view') AS page_views,
                COUNT(DISTINCT ue.ip_hash) FILTER (WHERE ue.ip_hash IS NOT NULL) AS unique_ips
            FROM usage_events ue
            {_USER_ROLE_JOIN}
            LEFT JOIN organisations o_org  ON o_org.id = ue.org_id
            LEFT JOIN organisations o_slug ON ue.org_id IS NULL
                                          AND ue.event_type = 'page_view'
                                          AND o_slug.slug = split_part(split_part(ue.path, '?', 1), '/', 2)
            WHERE ue.created_at >= NOW() - (:days * INTERVAL '1 day')
            {type_clause}
            {_role_filter(roles)}
            {search}
            GROUP BY 1, 2, 3
            ORDER BY hits DESC
            """
        ),
        params,
    )
    out = []
    for r in rows.mappings().all():
        out.append({
            "club_id": r["club_id"],
            "club_name": r["club_name"] or "Unattributed (marketing / admin / API)",
            "club_slug": r["club_slug"],
            "hits": int(r["hits"] or 0),
            "page_views": int(r["page_views"] or 0),
            "unique_ips": int(r["unique_ips"] or 0),
        })
    # Keep the attributed clubs first; the single Unattributed bucket sinks last.
    out.sort(key=lambda x: (x["club_id"] is None, -x["hits"]))
    return out


@router.get("/club-admin/usage/visitors")
async def visitors(
    days: int = 7,
    event_type: Optional[str] = None,
    anon_only: bool = False,
    q: Optional[str] = None,
    _: User = Depends(require_super_admin),
    db: AsyncSession = Depends(get_db),
):
    """Return-visitor analytics keyed on the stable visitor id (falling back to
    the hashed IP for legacy rows). We never store raw IPs.

      - visitors:    distinct visitors seen in the window
      - returning:   visitors whose first-ever hit predates the window
      - new:         visitors − returning
      - multi_day:   visitors active on ≥2 distinct days in the window
      - high_intent: visitors who viewed the contact or pricing page (a proxy —
                      they LOOKED, not necessarily submitted anything)
      - converted:   visitors who actually submitted an onboarding enquiry
                      (short CTA modal or full /contact form), matched on the
                      shared first-party visitor id — a real conversion, not a
                      proxy
      - identified:  visitors carrying a real first-party id (not IP-only)
      - avg_hits:    hits per visitor
    """
    days = max(1, min(days, 365))
    params: dict = {"days": days}
    type_clause = ""
    if event_type:
        type_clause = "AND ue.event_type = :etype"
        params["etype"] = event_type
    anon_clause = "AND ue.user_id IS NULL" if anon_only else ""
    search = _search_clause(q, params)
    row = (await db.execute(
        text(
            f"""
            WITH win AS (
                SELECT {_VKEY} AS vkey,
                       COUNT(*) AS hits,
                       COUNT(DISTINCT date_trunc('day', ue.created_at)) AS active_days,
                       bool_or(ue.visitor_id IS NOT NULL) AS identified,
                       bool_or({_INTENT_CONTACT} OR {_INTENT_PRICING}) AS high_intent,
                       bool_or(EXISTS (
                           SELECT 1 FROM club_onboarding_requests cor
                           WHERE cor.visitor_id = ue.visitor_id::text
                       )) AS converted
                FROM usage_events ue
                WHERE {_VKEY} IS NOT NULL
                  AND ue.created_at >= NOW() - (:days * INTERVAL '1 day')
                  {type_clause}
                  {anon_clause}
                  {search}
                GROUP BY {_VKEY}
            ),
            first_seen AS (
                SELECT {_VKEY} AS vkey, MIN(ue.created_at) AS first_ever
                FROM usage_events ue
                WHERE {_VKEY} IN (SELECT vkey FROM win)
                GROUP BY {_VKEY}
            )
            SELECT
                (SELECT COUNT(*) FROM win)                                  AS visitors,
                (SELECT COUNT(*) FROM win WHERE active_days >= 2)           AS multi_day,
                (SELECT COUNT(*) FROM win WHERE high_intent)               AS high_intent,
                (SELECT COUNT(*) FROM win WHERE converted)                 AS converted,
                (SELECT COUNT(*) FROM win WHERE identified)                AS identified,
                (SELECT COALESCE(SUM(hits), 0) FROM win)                    AS total_hits,
                (SELECT COUNT(*) FROM first_seen
                  WHERE first_ever < NOW() - (:days * INTERVAL '1 day'))    AS returning
            """
        ),
        params,
    )).mappings().first()
    visitors_n = int(row["visitors"] or 0)
    returning_n = int(row["returning"] or 0)
    total_hits = int(row["total_hits"] or 0)
    return {
        "days": days,
        "visitors": visitors_n,
        "returning": returning_n,
        "new": max(visitors_n - returning_n, 0),
        "multi_day": int(row["multi_day"] or 0),
        "high_intent": int(row["high_intent"] or 0),
        "converted": int(row["converted"] or 0),
        "identified": int(row["identified"] or 0),
        "total_hits": total_hits,
        "avg_hits": round(total_hits / visitors_n, 1) if visitors_n else 0.0,
        "returning_pct": round(100 * returning_n / visitors_n) if visitors_n else 0,
    }


@router.get("/club-admin/usage/top-routes")
async def top_routes(
    days: int = 7,
    limit: int = 30,
    role: Optional[list[str]] = Query(None),
    event_type: Optional[str] = None,
    q: Optional[str] = None,
    _: User = Depends(require_super_admin),
    db: AsyncSession = Depends(get_db),
):
    days = max(1, min(days, 365))
    limit = max(1, min(limit, 200))
    roles = _normalise_roles(role)
    params: dict = {"days": days, "lim": limit, **_role_params(roles)}
    type_clause = ""
    if event_type:
        type_clause = "AND ue.event_type = :etype"
        params["etype"] = event_type
    search = _search_clause(q, params)
    rows = await db.execute(
        text(
            f"""
            SELECT
                COALESCE(ue.route, ue.path) AS route_key,
                ue.event_type,
                COUNT(*) AS hits,
                COUNT(DISTINCT ue.user_id) FILTER (WHERE ue.user_id IS NOT NULL) AS unique_users,
                COUNT(DISTINCT ue.ip_hash) FILTER (WHERE ue.ip_hash IS NOT NULL) AS unique_ips,
                MAX(ue.created_at) AS last_hit
            FROM usage_events ue
            {_USER_ROLE_JOIN}
            WHERE ue.created_at >= NOW() - (:days * INTERVAL '1 day')
            {type_clause}
            {_role_filter(roles)}
            {search}
            GROUP BY route_key, ue.event_type
            ORDER BY hits DESC
            LIMIT :lim
            """
        ),
        params,
    )
    return [
        {
            "route": r["route_key"],
            "event_type": r["event_type"],
            "hits": int(r["hits"] or 0),
            "unique_users": int(r["unique_users"] or 0),
            "unique_ips": int(r["unique_ips"] or 0),
            "last_hit": r["last_hit"].isoformat() if r["last_hit"] else None,
        }
        for r in rows.mappings().all()
    ]


@router.get("/club-admin/usage/top-users")
async def top_users(
    days: int = 7,
    limit: int = 30,
    role: Optional[list[str]] = Query(None),
    q: Optional[str] = None,
    _: User = Depends(require_super_admin),
    db: AsyncSession = Depends(get_db),
):
    days = max(1, min(days, 365))
    limit = max(1, min(limit, 200))
    roles = _normalise_roles(role)
    params: dict = {"days": days, "lim": limit, **_role_params(roles)}
    search = _search_clause(q, params)
    rows = await db.execute(
        text(
            f"""
            SELECT
                ue.user_id,
                u.email AS user_email,
                u.display_name AS user_display_name,
                cm.role AS user_role,
                cm.club_id AS club_id,
                o.name AS club_name,
                o.slug AS club_slug,
                COUNT(*) AS hits,
                COUNT(DISTINCT COALESCE(ue.route, ue.path)) AS unique_routes,
                MAX(ue.created_at) AS last_hit
            FROM usage_events ue
            LEFT JOIN users u ON u.id = ue.user_id
            {_USER_ROLE_JOIN}
            LEFT JOIN organisations o ON o.id = cm.club_id
            WHERE ue.created_at >= NOW() - (:days * INTERVAL '1 day')
              AND ue.user_id IS NOT NULL
              {_role_filter(roles)}
              {search}
            GROUP BY ue.user_id, u.email, u.display_name, cm.role, cm.club_id, o.name, o.slug
            ORDER BY hits DESC
            LIMIT :lim
            """
        ),
        params,
    )
    return [
        {
            "user_id": str(r["user_id"]) if r["user_id"] else None,
            "user_email": r["user_email"],
            "user_display_name": r["user_display_name"],
            "user_role": r["user_role"],
            # A super admin's own membership row points at whatever club they
            # last acted as / were created under — not meaningful as "their
            # club", so the frontend shows "BetterCricket" for that role
            # instead; only club_admin/club_member rows carry a real club.
            "club_id": str(r["club_id"]) if r["club_id"] and r["user_role"] != "super_admin" else None,
            "club_name": r["club_name"] if r["user_role"] != "super_admin" else None,
            "club_slug": r["club_slug"] if r["user_role"] != "super_admin" else None,
            "hits": int(r["hits"] or 0),
            "unique_routes": int(r["unique_routes"] or 0),
            "last_hit": r["last_hit"].isoformat() if r["last_hit"] else None,
        }
        for r in rows.mappings().all()
    ]


@router.get("/club-admin/usage/recent")
async def recent_events(
    limit: int = 200,
    role: Optional[list[str]] = Query(None),
    event_type: Optional[str] = None,
    q: Optional[str] = None,
    _: User = Depends(require_super_admin),
    db: AsyncSession = Depends(get_db),
):
    limit = max(1, min(limit, 1000))
    roles = _normalise_roles(role)
    params: dict = {"lim": limit, **_role_params(roles)}
    extras = []
    if event_type:
        extras.append("AND ue.event_type = :etype")
        params["etype"] = event_type
    # _role_filter starts with AND; recent has its own WHERE 1=1 base so any
    # combination works.
    extras_sql = "\n".join(extras) + " " + _role_filter(roles) + " " + _search_clause(q, params)
    rows = await db.execute(
        text(
            f"""
            SELECT
                ue.id, ue.created_at, ue.event_type, ue.method, ue.path,
                ue.route, ue.status, ue.duration_ms, ue.user_id,
                ue.ip_hash, ue.referer,
                ue.country, ue.region, ue.city,
                u.email AS user_email, u.display_name AS user_display_name,
                cm.role AS user_role
            FROM usage_events ue
            LEFT JOIN users u ON u.id = ue.user_id
            {_USER_ROLE_JOIN}
            WHERE 1=1
            {extras_sql}
            ORDER BY ue.created_at DESC
            LIMIT :lim
            """
        ),
        params,
    )
    raw = rows.mappings().all()
    enriched = await _enrich_targets(db, raw)
    return enriched


# ─── Target-name resolution ──────────────────────────────────────────────────

# Frontend SPA paths whose first UUID is a player. Match `path`, not `route`.
_PLAYER_PATH_RES = (
    re.compile(r"^/players/([0-9a-f-]{36})", re.IGNORECASE),
)
_GAME_PATH_RES = (
    re.compile(r"^/games/([0-9a-f-]{36})", re.IGNORECASE),
    re.compile(r"^/match/([0-9a-f-]{36})", re.IGNORECASE),
    re.compile(r"^/scorecards/([0-9a-f-]{36})", re.IGNORECASE),
)


def _extract_target(path: Optional[str]) -> tuple[Optional[str], Optional[str]]:
    """Return (kind, uuid) for paths that point at a known entity.

    `kind` is one of 'player', 'game'. None if no match.
    """
    if not path:
        return (None, None)
    for r in _PLAYER_PATH_RES:
        m = r.match(path)
        if m:
            return ("player", m.group(1).lower())
    for r in _GAME_PATH_RES:
        m = r.match(path)
        if m:
            return ("game", m.group(1).lower())
    return (None, None)


async def _enrich_targets(db: AsyncSession, rows: list[dict]) -> list[dict]:
    """Attach `target_name` + `target_url` for rows whose path points at
    a known player or game. Two extra queries total (one per kind)."""
    player_ids: set[str] = set()
    game_ids: set[str] = set()
    for r in rows:
        kind, tid = _extract_target(r.get("path"))
        if kind == "player":
            player_ids.add(tid)
        elif kind == "game":
            game_ids.add(tid)

    player_names: dict[str, str] = {}
    if player_ids:
        result = await db.execute(
            text(
                "SELECT id, COALESCE(display_name_override, name) AS name "
                "FROM players WHERE id = ANY(:ids)"
            ),
            {"ids": [_uuid.UUID(x) for x in player_ids]},
        )
        for row in result.mappings().all():
            player_names[str(row["id"]).lower()] = row["name"]

    game_summaries: dict[str, str] = {}
    if game_ids:
        result = await db.execute(
            text(
                """
                SELECT g.id,
                       g.played_at,
                       g.home_team,
                       g.away_team
                FROM games g
                WHERE g.id = ANY(:ids)
                """
            ),
            {"ids": [_uuid.UUID(x) for x in game_ids]},
        )
        for row in result.mappings().all():
            home = row["home_team"] or "?"
            away = row["away_team"] or "?"
            when = row["played_at"].strftime("%d %b %Y") if row["played_at"] else ""
            game_summaries[str(row["id"]).lower()] = f"{home} v {away} · {when}".strip(" ·")

    out = []
    for r in rows:
        kind, tid = _extract_target(r.get("path"))
        target_name = None
        target_url = None
        if kind == "player" and tid in player_names:
            target_name = player_names[tid]
            target_url = f"/players/{tid}"
        elif kind == "game" and tid in game_summaries:
            target_name = game_summaries[tid]
            target_url = f"/games/{tid}"
        out.append({
            "id": r["id"],
            "created_at": r["created_at"].isoformat() if r["created_at"] else None,
            "event_type": r["event_type"],
            "method": r["method"],
            "path": r["path"],
            "route": r["route"],
            "status": r["status"],
            "duration_ms": r["duration_ms"],
            "user_id": str(r["user_id"]) if r["user_id"] else None,
            "user_email": r["user_email"],
            "user_display_name": r["user_display_name"],
            "user_role": r["user_role"],
            "ip_hash": r["ip_hash"],
            "referer": r["referer"],
            "country": r["country"],
            "region": r["region"],
            "city": r["city"],
            "target_kind": kind,
            "target_name": target_name,
            "target_url": target_url,
        })
    return out


# ─── Geographic breakdown ────────────────────────────────────────────────────

@router.get("/club-admin/usage/by-location")
async def by_location(
    days: int = 7,
    role: Optional[list[str]] = Query(None),
    event_type: Optional[str] = None,
    q: Optional[str] = None,
    _: User = Depends(require_super_admin),
    db: AsyncSession = Depends(get_db),
):
    """Top countries + cities for the window. Cities fall back to
    'Unknown city' when the ip-api lookup hasn't resolved them yet."""
    days = max(1, min(days, 365))
    roles = _normalise_roles(role)
    params: dict = {"days": days, **_role_params(roles)}
    type_clause = ""
    if event_type:
        type_clause = "AND ue.event_type = :etype"
        params["etype"] = event_type
    search = _search_clause(q, params)

    country_rows = await db.execute(
        text(
            f"""
            SELECT
                ue.country,
                COUNT(*) AS hits,
                COUNT(DISTINCT ue.ip_hash) FILTER (WHERE ue.ip_hash IS NOT NULL) AS unique_ips
            FROM usage_events ue
            {_USER_ROLE_JOIN}
            WHERE ue.created_at >= NOW() - (:days * INTERVAL '1 day')
            {type_clause}
            {_role_filter(roles)}
            {search}
            GROUP BY ue.country
            ORDER BY hits DESC
            LIMIT 25
            """
        ),
        params,
    )
    city_rows = await db.execute(
        text(
            f"""
            SELECT
                ue.country,
                ue.region,
                ue.city,
                COUNT(*) AS hits,
                COUNT(DISTINCT ue.ip_hash) FILTER (WHERE ue.ip_hash IS NOT NULL) AS unique_ips
            FROM usage_events ue
            {_USER_ROLE_JOIN}
            WHERE ue.created_at >= NOW() - (:days * INTERVAL '1 day')
              AND ue.city IS NOT NULL
            {type_clause}
            {_role_filter(roles)}
            {search}
            GROUP BY ue.country, ue.region, ue.city
            ORDER BY hits DESC
            LIMIT 25
            """
        ),
        params,
    )
    return {
        "by_country": [
            {
                "country": r["country"],
                "hits": int(r["hits"] or 0),
                "unique_ips": int(r["unique_ips"] or 0),
            }
            for r in country_rows.mappings().all()
        ],
        "by_city": [
            {
                "country": r["country"],
                "region": r["region"],
                "city": r["city"],
                "hits": int(r["hits"] or 0),
                "unique_ips": int(r["unique_ips"] or 0),
            }
            for r in city_rows.mappings().all()
        ],
    }


# ─── Campaigns / Meta ads attribution ────────────────────────────────────────

@router.get("/club-admin/usage/campaigns")
async def campaigns(
    days: int = 30,
    q: Optional[str] = None,
    _: User = Depends(require_super_admin),
    db: AsyncSession = Depends(get_db),
):
    """Marketing-attribution view of anonymous public page views — what our
    paid + organic campaigns actually drive.

    Every dimension is parsed at read time from the stored landing URL (the
    beacon keeps the full query string in ``path``), so it covers every event on
    record with no backfill. 'Meta' = Facebook + Instagram: the ads we run,
    detected by a meta/fb/ig ``utm_source`` or an ``fbclid``/``igshid`` on the
    URL. This is the click-through side — who arrived, which campaign/creative,
    where they landed, and whether they went on to a high-intent page.
    Impressions / spend / CTR live in Meta Ads Manager (would need the
    Marketing API) and are out of scope here.
    """
    days = max(1, min(days, 365))
    params: dict = {"days": days}
    search = _search_clause(q, params)

    base = (
        "ue.event_type = 'page_view' "
        "AND ue.user_id IS NULL "
        "AND split_part(ue.path, '?', 1) !~* '^/admin' "
        "AND ue.created_at >= NOW() - (:days * INTERVAL '1 day') "
    )

    # UTM dimensions read from the landing URL, preferring the dedicated column.
    cam = "COALESCE(NULLIF(ue.utm_campaign, ''), substring(ue.path from 'utm_campaign=([^&]+)'))"
    con = "COALESCE(NULLIF(ue.utm_content, ''),  substring(ue.path from 'utm_content=([^&]+)'))"
    src = "lower(COALESCE(NULLIF(ue.utm_source, ''), substring(ue.path from 'utm_source=([^&]+)')))"
    med = "lower(COALESCE(NULLIF(ue.utm_medium, ''), substring(ue.path from 'utm_medium=([^&]+)')))"
    land = "split_part(COALESCE(NULLIF(ue.landing_path, ''), ue.path), '?', 1)"

    meta_pred = (
        "(ue.traffic_source IN ('facebook', 'instagram') "
        f"OR {src} IN ('fb', 'facebook', 'meta', 'ig', 'instagram') "
        "OR ue.path ~* '(fbclid|igshid)=')"
    )

    # Headline — Meta (the ads we run).
    meta = (await db.execute(text(f"""
        SELECT
          COUNT(DISTINCT {_VKEY})                                            AS visitors,
          COUNT(*)                                                           AS views,
          COUNT(*) FILTER (WHERE ue.path ~* 'fbclid=')                       AS fbclid,
          COUNT(DISTINCT {_VKEY}) FILTER (
              WHERE {src} IN ('ig', 'instagram') OR ue.path ~* 'igshid=')    AS instagram,
          COUNT(DISTINCT {_VKEY}) FILTER (
              WHERE {src} IN ('fb', 'facebook', 'meta') OR ue.path ~* 'fbclid=') AS facebook,
          COUNT(DISTINCT {_VKEY}) FILTER (WHERE {med} ~ 'paid')              AS paid
        FROM usage_events ue
        WHERE {base} AND {meta_pred} {search}
    """), params)).mappings().first()

    # Every campaign / UTM combination — the searchable usage-tracking table.
    campaign_rows = (await db.execute(text(f"""
        SELECT {cam} AS campaign, {src} AS source, {med} AS medium,
               COUNT(DISTINCT {_VKEY}) AS visitors,
               COUNT(*) AS views,
               COUNT(DISTINCT {land}) AS landing_pages,
               MAX(ue.created_at) AS last_seen
        FROM usage_events ue
        WHERE {base} AND ({cam} IS NOT NULL OR {src} IS NOT NULL) {search}
        GROUP BY 1, 2, 3
        ORDER BY visitors DESC, views DESC
        LIMIT 60
    """), params)).mappings().all()

    # Ad creatives — utm_content is usually the ad name ({{ad.name}}).
    creative_rows = (await db.execute(text(f"""
        SELECT {con} AS content, {cam} AS campaign,
               COUNT(DISTINCT {_VKEY}) AS visitors, COUNT(*) AS views
        FROM usage_events ue
        WHERE {base} AND {con} IS NOT NULL {search}
        GROUP BY 1, 2 ORDER BY visitors DESC LIMIT 30
    """), params)).mappings().all()

    # Where Meta clicks land.
    landing_rows = (await db.execute(text(f"""
        SELECT {land} AS page,
               COUNT(DISTINCT {_VKEY}) AS visitors, COUNT(*) AS views
        FROM usage_events ue
        WHERE {base} AND {meta_pred} {search}
        GROUP BY 1 ORDER BY visitors DESC LIMIT 15
    """), params)).mappings().all()

    # Did the ad click do anything? Meta visitors who went on to a high-intent
    # page (pricing / contact) — the closest signal to a conversion we hold.
    conv = (await db.execute(text(f"""
        WITH mv AS (
            SELECT DISTINCT {_VKEY} AS vkey
            FROM usage_events ue
            WHERE {base} AND {meta_pred} AND {_VKEY} IS NOT NULL {search}
        ),
        intent AS (
            SELECT DISTINCT {_VKEY} AS vkey
            FROM usage_events ue
            WHERE ue.event_type = 'page_view'
              AND ue.created_at >= NOW() - (:days * INTERVAL '1 day')
              AND split_part(ue.path, '?', 1) ~* '^/(pricing|contact)(/|$)'
        )
        SELECT (SELECT COUNT(*) FROM mv)                                       AS visitors,
               (SELECT COUNT(*) FROM mv WHERE vkey IN (SELECT vkey FROM intent)) AS reached_intent
    """), params)).mappings().first()

    def _u(v):
        return unquote_plus(v) if v else None

    conv_v = int(conv["visitors"] or 0)
    conv_i = int(conv["reached_intent"] or 0)
    return {
        "days": days,
        "meta": {
            "visitors": int(meta["visitors"] or 0),
            "views": int(meta["views"] or 0),
            "fbclid": int(meta["fbclid"] or 0),
            "facebook": int(meta["facebook"] or 0),
            "instagram": int(meta["instagram"] or 0),
            "paid": int(meta["paid"] or 0),
        },
        "conversion": {
            "visitors": conv_v,
            "reached_intent": conv_i,
            "pct": round(100 * conv_i / conv_v) if conv_v else 0,
        },
        "campaigns": [
            {
                "campaign": _u(r["campaign"]),
                "source": _u(r["source"]),
                "medium": _u(r["medium"]),
                "visitors": int(r["visitors"] or 0),
                "views": int(r["views"] or 0),
                "landing_pages": int(r["landing_pages"] or 0),
                "last_seen": r["last_seen"].isoformat() if r["last_seen"] else None,
            }
            for r in campaign_rows
        ],
        "creatives": [
            {
                "content": _u(r["content"]),
                "campaign": _u(r["campaign"]),
                "visitors": int(r["visitors"] or 0),
                "views": int(r["views"] or 0),
            }
            for r in creative_rows
        ],
        "landing": [
            {
                "page": r["page"],
                "label": _page_label(r["page"]),
                "visitors": int(r["visitors"] or 0),
                "views": int(r["views"] or 0),
            }
            for r in landing_rows
        ],
    }


# ─── Session / dwell duration ────────────────────────────────────────────────
#
# "Session" is never stored — it's a read-time grouping of a visitor's
# page_view timestamps into visits separated by a ≥30-minute gap (the
# industry-standard session-boundary heuristic; matches GA4's default). A
# session's duration is the span between its first and last page_view PLUS
# the final page's own dwell time (from its page_exit beacon, matched by
# visitor + path + nearest-following timestamp) — without that tail, a
# single-page (bounce) session would always read as 0ms even though the
# visitor may have read the page for a full minute before leaving.

_SESSION_DURATION_SQL = f"""
WITH pv AS (
    SELECT {_VKEY} AS vkey, ue.created_at, ue.id,
           split_part(ue.path, '?', 1) AS page
    FROM usage_events ue
    WHERE ue.event_type = 'page_view'
      AND {_VKEY} IS NOT NULL
      AND ue.created_at >= NOW() - (:days * INTERVAL '1 day')
),
gapped AS (
    SELECT *, created_at - LAG(created_at) OVER (PARTITION BY vkey ORDER BY created_at, id) AS gap
    FROM pv
),
sessioned AS (
    SELECT *, SUM(CASE WHEN gap IS NULL OR gap > INTERVAL '30 minutes' THEN 1 ELSE 0 END)
        OVER (PARTITION BY vkey ORDER BY created_at, id) AS session_num
    FROM gapped
),
session_bounds AS (
    SELECT vkey, session_num,
           MIN(created_at) AS start_ts,
           MAX(created_at) AS end_ts,
           COUNT(*) AS pages,
           (ARRAY_AGG(page ORDER BY created_at DESC))[1] AS last_page
    FROM sessioned
    GROUP BY vkey, session_num
),
last_exit AS (
    SELECT DISTINCT ON (sb.vkey, sb.session_num)
           sb.vkey, sb.session_num, pe.time_on_page_ms
    FROM session_bounds sb
    JOIN usage_events pe
      ON pe.event_type = 'page_exit'
     AND COALESCE(pe.visitor_id::text, pe.ip_hash) = sb.vkey
     AND split_part(pe.path, '?', 1) = sb.last_page
     AND pe.created_at >= sb.end_ts
     AND pe.created_at <= sb.end_ts + INTERVAL '10 minutes'
    ORDER BY sb.vkey, sb.session_num, pe.created_at ASC
),
durations AS (
    SELECT sb.vkey, sb.session_num, sb.pages,
           (EXTRACT(EPOCH FROM (sb.end_ts - sb.start_ts)) * 1000
             + COALESCE(le.time_on_page_ms, 0))::bigint AS duration_ms
    FROM session_bounds sb
    LEFT JOIN last_exit le ON le.vkey = sb.vkey AND le.session_num = sb.session_num
)
"""


@router.get("/club-admin/usage/session-duration")
async def session_duration(
    days: int = 7,
    _: User = Depends(require_super_admin),
    db: AsyncSession = Depends(get_db),
):
    """Session-duration + per-page dwell-time analytics.

    A "session" is derived on read (see _SESSION_DURATION_SQL above) — there
    is no stored session table. ``avg_ms``/``median_ms`` cover full visits
    (possibly several pages); ``top_pages`` is per-page average dwell time
    from the page_exit beacon directly, independent of session grouping.
    """
    days = max(1, min(days, 365))
    params = {"days": days}

    row = (await db.execute(text(f"""
        {_SESSION_DURATION_SQL}
        SELECT
            COUNT(*) AS sessions,
            AVG(duration_ms) AS avg_ms,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY duration_ms) AS median_ms,
            AVG(pages) AS avg_pages,
            COUNT(*) FILTER (WHERE duration_ms < 10000)                          AS b_10s,
            COUNT(*) FILTER (WHERE duration_ms >= 10000  AND duration_ms < 30000)  AS b_30s,
            COUNT(*) FILTER (WHERE duration_ms >= 30000  AND duration_ms < 60000)  AS b_1m,
            COUNT(*) FILTER (WHERE duration_ms >= 60000  AND duration_ms < 180000) AS b_3m,
            COUNT(*) FILTER (WHERE duration_ms >= 180000 AND duration_ms < 600000) AS b_10m,
            COUNT(*) FILTER (WHERE duration_ms >= 600000)                         AS b_10m_plus
        FROM durations
    """), params)).mappings().first()

    top_pages = (await db.execute(text("""
        SELECT split_part(ue.path, '?', 1) AS page,
               AVG(ue.time_on_page_ms) AS avg_ms,
               COUNT(*) AS samples
        FROM usage_events ue
        WHERE ue.event_type = 'page_exit'
          AND ue.time_on_page_ms IS NOT NULL
          AND ue.created_at >= NOW() - (:days * INTERVAL '1 day')
        GROUP BY 1
        HAVING COUNT(*) >= 3
        ORDER BY samples DESC
        LIMIT 20
    """), params)).mappings().all()

    sessions_n = int(row["sessions"] or 0)
    return {
        "days": days,
        "sessions": sessions_n,
        "avg_session_ms": round(float(row["avg_ms"])) if row["avg_ms"] is not None else 0,
        "median_session_ms": round(float(row["median_ms"])) if row["median_ms"] is not None else 0,
        "avg_pages_per_session": round(float(row["avg_pages"]), 1) if row["avg_pages"] is not None else 0.0,
        "distribution": [
            {"bucket": "<10s",   "count": int(row["b_10s"] or 0)},
            {"bucket": "10–30s", "count": int(row["b_30s"] or 0)},
            {"bucket": "30s–1m", "count": int(row["b_1m"] or 0)},
            {"bucket": "1–3m",   "count": int(row["b_3m"] or 0)},
            {"bucket": "3–10m",  "count": int(row["b_10m"] or 0)},
            {"bucket": "10m+",   "count": int(row["b_10m_plus"] or 0)},
        ],
        "top_pages": [
            {
                "page": r["page"],
                "label": _page_label(r["page"]),
                "avg_time_on_page_ms": round(float(r["avg_ms"])) if r["avg_ms"] is not None else 0,
                "samples": int(r["samples"] or 0),
            }
            for r in top_pages
        ],
    }


# ─── Visitor journey ──────────────────────────────────────────────────────────

@router.get("/club-admin/usage/journey")
async def visitor_journey(
    visitor_id: str = Query(...),
    limit: int = 300,
    _: User = Depends(require_super_admin),
    db: AsyncSession = Depends(get_db),
):
    """One visitor's full ordered page-view path, split into sessions
    (≥30-minute gap = a new visit) with per-page dwell time attached from the
    matching page_exit beacon. This is the "what did they actually click
    through, and in what order" view — every other Usage endpoint aggregates
    across visitors; this one reconstructs a single visitor's journey.

    Accepts either the first-party visitor_id (localStorage UUID) or, for
    legacy rows written before that existed, the hashed IP — same identity
    key (_VKEY) every other visitor-scoped endpoint uses.
    """
    limit = max(1, min(limit, 1000))
    rows = (await db.execute(text(f"""
        SELECT ue.id, ue.created_at, ue.event_type, ue.path, ue.route,
               ue.utm_source, ue.utm_medium, ue.utm_campaign, ue.utm_content,
               ue.utm_id, ue.traffic_source, ue.time_on_page_ms
        FROM usage_events ue
        WHERE {_VKEY} = :vkey
          AND ue.event_type IN ('page_view', 'page_exit')
        ORDER BY ue.created_at ASC
        LIMIT :lim
    """), {"vkey": visitor_id, "lim": limit})).mappings().all()

    # Merge each page_view with its following page_exit (same page, next in
    # the stream) into one step, and split into sessions on a ≥30-min gap.
    steps: list[dict] = []
    pending_exit_by_page: dict[str, dict] = {}
    for r in rows:
        page = (r["path"] or "").split("?")[0]
        if r["event_type"] == "page_exit":
            pending_exit_by_page[page] = r
            continue
        steps.append({
            "created_at": r["created_at"],
            "path": r["path"],
            "label": _page_label(r["path"]),
            "utm_source": r["utm_source"],
            "utm_medium": r["utm_medium"],
            "utm_campaign": r["utm_campaign"],
            "utm_content": r["utm_content"],
            "utm_id": r["utm_id"],
            "traffic_source": r["traffic_source"],
            "time_on_page_ms": None,
        })
    # Attach dwell time: a page_exit is matched to the MOST RECENT step for
    # that same page path (handles a visitor revisiting the same page twice).
    for page, exit_row in pending_exit_by_page.items():
        candidates = [s for s in steps if s["path"].split("?")[0] == page
                      and s["created_at"] <= exit_row["created_at"]]
        if candidates:
            candidates[-1]["time_on_page_ms"] = exit_row["time_on_page_ms"]

    # Session split.
    sessions: list[dict] = []
    current: list[dict] = []
    prev_ts = None
    for s in steps:
        if prev_ts is not None and (s["created_at"] - prev_ts).total_seconds() > 1800:
            sessions.append(current)
            current = []
        current.append(s)
        prev_ts = s["created_at"]
    if current:
        sessions.append(current)

    def _fmt(step):
        return {
            "created_at": step["created_at"].isoformat() if step["created_at"] else None,
            "path": step["path"],
            "label": step["label"],
            "time_on_page_ms": step["time_on_page_ms"],
            "utm_source": step["utm_source"],
            "utm_medium": step["utm_medium"],
            "utm_campaign": step["utm_campaign"],
            "utm_content": step["utm_content"],
            "utm_id": step["utm_id"],
            "traffic_source": step["traffic_source"],
        }

    return {
        "visitor_id": visitor_id,
        "total_page_views": len(steps),
        "sessions": [
            {
                "started_at": sess[0]["created_at"].isoformat() if sess else None,
                "ended_at": sess[-1]["created_at"].isoformat() if sess else None,
                "steps": [_fmt(s) for s in sess],
            }
            for sess in sessions
        ],
    }


# ─── Current background processes ────────────────────────────────────────────

# How a raw sync_runs.kind maps to a human label on the panel.
_SYNC_KIND_LABEL = {
    "org_full": "Sync (Sync Now)",
    "org_recent": "Results sync (scheduled)",
    "org_hard_refresh": "Full Rebuild",
    "player_deep": "Player deep sync",
}

# Self-serve registration funnel step → human label + 1-based position, so the
# panel can show "which step they're at" (see public_self_serve.FUNNEL_STEPS and
# services/meta_ads.REGISTRATION_STEP_ORDER — kept in the same order here).
_REG_STEP_ORDER = [
    ("club_prepared", "Club selected"),
    ("admin_details_completed", "Admin details completed"),
    ("email_code_sent", "Verification code sent"),
    ("email_verified", "Email verified"),
    ("acknowledgements_accepted", "Terms & privacy accepted"),
    ("submit_attempted", "Submit attempted"),
    ("registration_completed", "Registration completed"),
]
_REG_STEP_LABEL = {k: (i + 1, lbl) for i, (k, lbl) in enumerate(_REG_STEP_ORDER)}
_REG_STEP_TOTAL = len(_REG_STEP_ORDER)


@router.get("/club-admin/usage/background-processes")
async def background_processes(
    _: User = Depends(require_super_admin),
    db: AsyncSession = Depends(get_db),
):
    """What long-running work is happening on the platform right now — the
    Super Admin Usage page's Current Background Processes panel. Four groups:

    * ``syncs`` — every ``sync_runs`` row still ``running`` or ``paused``
      (Full Rebuild / Sync Now / player deep sync), with the club + who started
      it, how long it's been going, its live phase and % complete (read from the
      run's ``stats`` progress keys), and whether it was auto-resumed after a
      restart.
    * ``iq_prewarm`` — in-process BetterIQ opponent-dossier prewarms.
    * ``registrations`` — self-serve trial signups mid-flow (public wizard
      beacons that haven't reached ``registration_completed``), showing which
      step the prospect is at.
    * ``onboarding`` — clubs whose admins are actively working the Setup Wizard
      (progress touched recently), with the most recent acting user.

    All read-only and cheap; the panel polls this every few seconds.
    """
    now = datetime.now(timezone.utc)

    def _secs(ts) -> Optional[int]:
        if not ts:
            return None
        if ts.tzinfo is None:
            ts = ts.replace(tzinfo=timezone.utc)
        return max(0, int((now - ts).total_seconds()))

    # Idle-abandonment limits (super-admin tunable via the panel's Settings
    # button). A prospect/club idle past their group's limit is treated as
    # abandoned and dropped from the panel. See services/platform_settings.
    idle = await ps.get_background_process_settings(db)
    reg_idle_minutes = idle["registration_minutes"]
    onb_idle_minutes = idle["onboarding_minutes"]

    # ── Syncs (running or paused) ────────────────────────────────────────────
    sync_rows = (await db.execute(text("""
        SELECT sr.id, sr.org_id, sr.kind, sr.status, sr.started_at, sr.updated_at,
               sr.stats, sr.player_id,
               o.name AS club_name,
               u.email AS user_email, u.display_name AS user_display_name,
               p.name AS player_name, p.display_name_override AS player_display_name
        FROM sync_runs sr
        LEFT JOIN organisations o ON o.id = sr.org_id
        LEFT JOIN users u ON u.id = sr.triggered_by_user_id
        LEFT JOIN players p ON p.id = sr.player_id
        WHERE sr.status IN ('running', 'paused')
        ORDER BY sr.started_at DESC
    """))).mappings().all()

    syncs = []
    for r in sync_rows:
        st = r["stats"] or {}
        pct = st.get("progress_pct")
        syncs.append({
            "run_id": str(r["id"]),
            "kind": r["kind"],
            "kind_label": _SYNC_KIND_LABEL.get(r["kind"], r["kind"]),
            "status": r["status"],
            "club_id": str(r["org_id"]) if r["org_id"] else None,
            "club_name": r["club_name"],
            "player_name": r["player_display_name"] or r["player_name"],
            "started_by": (r["user_display_name"] or r["user_email"]) if r["user_email"] else None,
            "started_by_email": r["user_email"],
            "started_at": r["started_at"].isoformat() if r["started_at"] else None,
            "updated_at": r["updated_at"].isoformat() if r["updated_at"] else None,
            "running_seconds": _secs(r["started_at"]),
            "phase": st.get("progress_phase"),
            "pct": int(pct) if isinstance(pct, (int, float)) else None,
            "done": st.get("progress_done"),
            "total": st.get("progress_total"),
            "resumed_after_restart": bool(st.get("resumed_after_restart")),
        })

    # Orgs with a sync/rebuild currently in flight. Used below as the sole
    # exception to the onboarding idle-drop: the Setup Wizard's first step
    # (full_rebuild) kicks off a long async sync, so a club that starts it and
    # leaves the page LOOKS idle on the wizard while the rebuild runs. That's not
    # abandonment — the job is still going and already shows in the Syncs panel —
    # so we keep such a club on the onboarding list regardless of idle time.
    active_sync_org_ids = {
        str(r["org_id"]) for r in sync_rows if r["org_id"]
    }

    # ── BetterIQ opponent-dossier prewarms (in-process) ──────────────────────
    from app.services import iq_prewarm
    prewarms = []
    pw_snap = iq_prewarm.snapshot_all()
    if pw_snap:
        pw_ids = [s["org_id"] for s in pw_snap]
        name_rows = (await db.execute(text("""
            SELECT id::text AS id, name FROM organisations WHERE id = ANY(CAST(:ids AS uuid[]))
        """), {"ids": pw_ids})).mappings().all()
        names = {row["id"]: row["name"] for row in name_rows}
        for s in pw_snap:
            started = s.get("started_at")
            started_dt = None
            if started:
                try:
                    started_dt = datetime.fromisoformat(started)
                except (ValueError, TypeError):
                    started_dt = None
            prewarms.append({
                "org_id": s["org_id"],
                "club_name": names.get(s["org_id"]),
                "done": s.get("done"),
                "total": s.get("total"),
                "current": s.get("current"),
                "started_at": started,
                "running_seconds": _secs(started_dt),
            })

    # ── Self-serve registrations mid-flow (public wizard beacons) ────────────
    # A visitor is "in progress" if they've beaconed a self_serve_step within the
    # registration idle limit but never reached registration_completed. Group per
    # visitor, keep the furthest step reached (highest step index). Because the
    # window IS the idle limit, a prospect whose last step beacon is older than
    # the limit falls out of this query entirely — i.e. they're dropped from the
    # panel, treated as having abandoned the signup.
    reg_rows = (await db.execute(text("""
        WITH steps AS (
            SELECT visitor_id, route AS step, created_at, metadata
            FROM usage_events
            WHERE event_type = 'self_serve_step'
              AND visitor_id IS NOT NULL
              AND created_at >= NOW() - (:reg_idle_minutes * INTERVAL '1 minute')
        ),
        done AS (
            SELECT DISTINCT visitor_id FROM steps WHERE step = 'registration_completed'
        )
        SELECT s.visitor_id,
               MIN(s.created_at) AS first_at,
               MAX(s.created_at) AS last_at,
               (ARRAY_AGG(s.metadata ORDER BY s.created_at DESC)
                 FILTER (WHERE jsonb_exists(s.metadata, 'club_name')))[1] AS club_meta,
               ARRAY_AGG(DISTINCT s.step) AS steps
        FROM steps s
        WHERE s.visitor_id NOT IN (SELECT visitor_id FROM done)
        GROUP BY s.visitor_id
        ORDER BY MAX(s.created_at) DESC
        LIMIT 50
    """), {"reg_idle_minutes": reg_idle_minutes})).mappings().all()

    registrations = []
    for r in reg_rows:
        reached = [s for s in (r["steps"] or []) if s in _REG_STEP_LABEL]
        if not reached:
            continue
        # Furthest step = the one with the highest order index.
        best_key = max(reached, key=lambda s: _REG_STEP_LABEL[s][0])
        idx, label = _REG_STEP_LABEL[best_key]
        club_meta = r["club_meta"] or {}
        registrations.append({
            "visitor_id": r["visitor_id"],
            "club_name": club_meta.get("club_name"),
            "step_key": best_key,
            "step_label": label,
            "step_index": idx,
            "step_total": _REG_STEP_TOTAL,
            "started_at": r["first_at"].isoformat() if r["first_at"] else None,
            "last_at": r["last_at"].isoformat() if r["last_at"] else None,
            "running_seconds": _secs(r["first_at"]),
            "idle_seconds": _secs(r["last_at"]),
        })

    # ── Clubs actively working the Setup Wizard ──────────────────────────────
    # A club shows here while its wizard progress was touched within the
    # onboarding idle limit (time since ows.updated_at) — a club idle past that
    # is treated as having abandoned setup and drops off the panel.
    # THE ONE EXCEPTION: a club with a sync/rebuild still in flight is kept no
    # matter how idle it looks. The wizard's first step (full_rebuild) fires a
    # long async sync; the admin typically starts it and leaves the page, so the
    # wizard state goes stale while the rebuild runs. That job already shows in
    # the Syncs panel and is genuinely still working, so it's not abandonment —
    # hence the OR EXISTS(running sync) below.
    # Onboarding state is org-scoped, but the club has a known owner: its
    # primary admin (the person who registered it — club_memberships.is_primary_admin).
    # That's who we identify as running the onboarding. The most recent
    # setup_wizard_* audit entry is kept as a fallback for the rare club whose
    # primary admin flag isn't set (or where a different admin is doing the work).
    onboard_rows = (await db.execute(text("""
        SELECT ows.organisation_id AS org_id, ows.updated_at,
               ows.completed_steps, ows.skipped_steps, ows.na_steps,
               o.name AS club_name,
               pa.email AS admin_email, pa.display_name AS admin_display_name,
               au.email AS actor_email, au.display_name AS actor_display_name
        FROM onboarding_wizard_state ows
        JOIN organisations o ON o.id = ows.organisation_id
        LEFT JOIN LATERAL (
            SELECT u.email, u.display_name
            FROM club_memberships cm
            JOIN users u ON u.id = cm.user_id
            WHERE cm.club_id = ows.organisation_id AND cm.is_primary_admin IS TRUE
            ORDER BY cm.created_at ASC
            LIMIT 1
        ) pa ON TRUE
        LEFT JOIN LATERAL (
            SELECT user_id
            FROM audit_logs
            WHERE org_id = ows.organisation_id
              AND action LIKE 'setup_wizard_%'
              AND created_at >= NOW() - INTERVAL '30 minutes'
            ORDER BY created_at DESC
            LIMIT 1
        ) al ON TRUE
        LEFT JOIN users au ON au.id = al.user_id
        WHERE ows.updated_at >= NOW() - (:onb_idle_minutes * INTERVAL '1 minute')
           OR EXISTS (
                SELECT 1 FROM sync_runs sr2
                WHERE sr2.org_id = ows.organisation_id
                  AND sr2.status IN ('running', 'paused')
           )
        ORDER BY ows.updated_at DESC
        LIMIT 50
    """), {"onb_idle_minutes": onb_idle_minutes})).mappings().all()

    onboarding = []
    for r in onboard_rows:
        done = len(r["completed_steps"] or [])
        addressed = done + len(r["skipped_steps"] or []) + len(r["na_steps"] or [])
        primary_admin = (r["admin_display_name"] or r["admin_email"]) if r["admin_email"] else None
        actor = (r["actor_display_name"] or r["actor_email"]) if r["actor_email"] else None
        onboarding.append({
            "org_id": str(r["org_id"]),
            "club_name": r["club_name"],
            "done": done,
            "addressed": addressed,
            "last_activity_at": r["updated_at"].isoformat() if r["updated_at"] else None,
            "idle_seconds": _secs(r["updated_at"]),
            # True when this club is only still listed because a sync/rebuild is
            # running (the full_rebuild exception) rather than recent wizard
            # activity — lets the panel say "sync running" instead of "active".
            "sync_running": str(r["org_id"]) in active_sync_org_ids,
            # Who owns the onboarding: the club's primary admin, else whoever
            # last touched a wizard step.
            "actor": primary_admin or actor,
            "primary_admin": primary_admin,
        })

    return {
        "generated_at": now.isoformat(),
        "idle_limits": {
            "registration_minutes": reg_idle_minutes,
            "onboarding_minutes": onb_idle_minutes,
        },
        "syncs": syncs,
        "iq_prewarm": prewarms,
        "registrations": registrations,
        "onboarding": onboarding,
    }


@router.get("/club-admin/usage/background-settings")
async def get_background_settings(
    _: User = Depends(require_super_admin),
    db: AsyncSession = Depends(get_db),
):
    """The idle-abandonment limits for the Current Background Processes panel —
    read by the panel's Settings dialog. See services/platform_settings."""
    s = await ps.get_background_process_settings(db)
    return {
        **s,
        "min_minutes": ps.IDLE_MINUTES_MIN,
        "max_minutes": ps.IDLE_MINUTES_MAX,
    }


class BackgroundSettingsUpdate(BaseModel):
    registration_minutes: Optional[int] = None
    onboarding_minutes: Optional[int] = None


@router.patch("/club-admin/usage/background-settings")
async def patch_background_settings(
    payload: BackgroundSettingsUpdate,
    _: User = Depends(require_super_admin),
    db: AsyncSession = Depends(get_db),
):
    """Set either idle limit (whole minutes). Values are clamped server-side to
    [min_minutes, max_minutes]."""
    s = await ps.update_background_process_settings(
        db,
        registration_minutes=payload.registration_minutes,
        onboarding_minutes=payload.onboarding_minutes,
    )
    return {
        **s,
        "min_minutes": ps.IDLE_MINUTES_MIN,
        "max_minutes": ps.IDLE_MINUTES_MAX,
    }


# ─── Live / realtime ─────────────────────────────────────────────────────────

@router.get("/club-admin/usage/live")
async def live(
    _: User = Depends(require_super_admin),
    db: AsyncSession = Depends(get_db),
):
    """One realtime snapshot of the public site, polled by the Usage page:
    active visitors across time windows, page views per minute for the last
    half hour, a live feed of recent page views, and the top pages + traffic
    sources for the last 24h. Anonymous public page views only — logged-in
    admins/members and the /admin app are excluded so the numbers reflect real
    visitors, not us."""
    src_ue = _src_sql("ue")
    # Constant filter: anonymous public page views (no /admin, no API).
    base = (
        "ue.event_type = 'page_view' "
        "AND ue.user_id IS NULL "
        "AND split_part(ue.path, '?', 1) !~* '^/admin'"
    )
    # "Right now" also counts heartbeats (see /usage/heartbeat) — a tab that's
    # sat open on one page with no navigation still pings every ~25s, so this
    # reflects someone actually having the page open, not just a recent nav.
    _NOW_WINDOW = "45 seconds"
    online_base = (
        "ue.event_type IN ('page_view', 'heartbeat') "
        "AND ue.user_id IS NULL "
        "AND split_part(ue.path, '?', 1) !~* '^/admin'"
    )

    active = (await db.execute(text(f"""
        WITH ev AS (
            SELECT {_VKEY} AS vkey, ue.created_at
            FROM usage_events ue
            WHERE {base} AND ue.created_at >= NOW() - INTERVAL '7 days'
        )
        SELECT
          COUNT(DISTINCT vkey) FILTER (WHERE created_at >= NOW() - INTERVAL '30 minutes') AS v_m30,
          COUNT(*)             FILTER (WHERE created_at >= NOW() - INTERVAL '30 minutes') AS p_m30,
          COUNT(DISTINCT vkey) FILTER (WHERE created_at >= NOW() - INTERVAL '24 hours')   AS v_day,
          COUNT(*)             FILTER (WHERE created_at >= NOW() - INTERVAL '24 hours')   AS p_day,
          COUNT(DISTINCT vkey) AS v_week,
          COUNT(*)             AS p_week
        FROM ev
    """))).mappings().first()

    # v_now (is anyone here at all) still counts heartbeats, so a visitor
    # parked on one page with no fresh navigation still reads as active. But
    # p_now is surfaced to the frontend as "views" alongside three other
    # windows whose own "views" are real page_view counts only (see `ev`
    # above) — counting heartbeats here too silently inflated it (a single
    # idle tab can rack up 2-3 heartbeat pings inside one 45s window with no
    # new page load behind any of them), making "Active now" report fresh
    # view activity the Live feed below has no matching row for.
    now_active = (await db.execute(text(f"""
        SELECT COUNT(DISTINCT {_VKEY}) AS v_now,
               COUNT(*) FILTER (WHERE ue.event_type = 'page_view') AS p_now
        FROM usage_events ue
        WHERE {online_base} AND ue.created_at >= NOW() - INTERVAL '{_NOW_WINDOW}'
    """))).mappings().first()

    per_minute = (await db.execute(text(f"""
        SELECT gs AS minute, COALESCE(c.views, 0) AS views
        FROM generate_series(
            date_trunc('minute', NOW()) - INTERVAL '29 minutes',
            date_trunc('minute', NOW()),
            INTERVAL '1 minute'
        ) gs
        LEFT JOIN (
            SELECT date_trunc('minute', ue.created_at) AS m, COUNT(*) AS views
            FROM usage_events ue
            WHERE {base} AND ue.created_at >= NOW() - INTERVAL '30 minutes'
            GROUP BY 1
        ) c ON c.m = gs
        ORDER BY gs
    """))).mappings().all()

    top_pages = (await db.execute(text(f"""
        SELECT split_part(ue.path, '?', 1) AS page,
               COUNT(*) AS views,
               COUNT(DISTINCT {_VKEY}) AS visitors
        FROM usage_events ue
        WHERE {base} AND ue.created_at >= NOW() - INTERVAL '24 hours'
        GROUP BY 1 ORDER BY views DESC LIMIT 15
    """))).mappings().all()

    sources = (await db.execute(text(f"""
        SELECT src AS source, COUNT(*) AS views, COUNT(DISTINCT vkey) AS visitors
        FROM (
            SELECT {_VKEY} AS vkey, {src_ue} AS src
            FROM usage_events ue
            WHERE {base} AND ue.created_at >= NOW() - INTERVAL '24 hours'
        ) s
        GROUP BY src ORDER BY visitors DESC
    """))).mappings().all()

    utms = (await db.execute(text(f"""
        SELECT lower(substring(ue.path from 'utm_source=([^&]+)'))  AS utm_source,
               substring(ue.path from 'utm_campaign=([^&]+)')       AS utm_campaign,
               substring(ue.path from 'utm_medium=([^&]+)')         AS utm_medium,
               COUNT(*) AS views,
               COUNT(DISTINCT {_VKEY}) AS visitors,
               MAX(ue.created_at) AS last_seen
        FROM usage_events ue
        WHERE {base}
          AND ue.created_at >= NOW() - INTERVAL '24 hours'
          AND ue.path ~* 'utm_source='
        GROUP BY 1, 2, 3 ORDER BY views DESC LIMIT 20
    """))).mappings().all()

    # Which club an anonymous visitor is associated with — NOT which club's
    # page they happen to be looking at (a stranger reading Applecross's
    # public scorecard isn't "associated with Applecross"), but who sent
    # them: an outreach email/share-link's own utm_id/utm_source matching a
    # club's tracking code (marketing_clubs.utm_code), or a manually-set
    # alias for a raw value that doesn't literally equal a club's code
    # (marketing_utm_aliases — e.g. a rep's name used as utm_source). Reuses
    # the exact alias/utm_code resolution the Club Directory's own prospect
    # scoring runs (club_directory._resolved_cid_sql), with the path-derived
    # branches disabled (path_code -> NULL) so landing on a club's own page
    # with no tracked link behind it never attributes on its own.
    _live_club_cid = _resolved_cid_sql("ue.utm_id", "ue.utm_source", "NULL")

    recent = (await db.execute(text(f"""
        WITH ev AS (
            SELECT ue.*, ({_live_club_cid}) AS resolved_club_cid
            FROM usage_events ue
            WHERE {base}
            ORDER BY ue.created_at DESC LIMIT 60
        )
        SELECT ev.created_at,
               split_part(ev.path, '?', 1) AS page,
               ev.country, ev.region, ev.city, ev.user_agent,
               {_src_sql('ev')} AS source,
               lower(substring(ev.path from 'utm_source=([^&]+)')) AS utm_source,
               substring(ev.path from 'utm_campaign=([^&]+)') AS utm_campaign,
               mc.id AS club_id, mc.name AS club_name,
               mc.existing_org_id AS club_org_id,
               EXISTS (
                   SELECT 1 FROM usage_events h
                   WHERE {online_base.replace('ue.', 'h.')}
                     AND h.created_at >= NOW() - INTERVAL '{_NOW_WINDOW}'
                     AND {_VKEY.replace('ue.', 'h.')} = {_VKEY.replace('ue.', 'ev.')}
               ) AS is_online
        FROM ev
        LEFT JOIN marketing_clubs mc ON mc.id::text = ev.resolved_club_cid
        ORDER BY ev.created_at DESC
    """))).mappings().all()

    def _u(v):
        return unquote_plus(v) if v else None

    return {
        "active": {
            "now":   {"visitors": int(now_active["v_now"] or 0), "views": int(now_active["p_now"] or 0)},
            "m30":   {"visitors": int(active["v_m30"] or 0),  "views": int(active["p_m30"] or 0)},
            "today": {"visitors": int(active["v_day"] or 0),  "views": int(active["p_day"] or 0)},
            "week":  {"visitors": int(active["v_week"] or 0), "views": int(active["p_week"] or 0)},
        },
        "per_minute": [
            {"minute": r["minute"].isoformat() if r["minute"] else None,
             "views": int(r["views"] or 0)}
            for r in per_minute
        ],
        "top_pages": [
            {"page": r["page"], "label": _page_label(r["page"]),
             "views": int(r["views"] or 0), "visitors": int(r["visitors"] or 0)}
            for r in top_pages
        ],
        "sources": [
            {"source": r["source"] or "direct", "views": int(r["views"] or 0),
             "visitors": int(r["visitors"] or 0)}
            for r in sources
        ],
        "utms": [
            {"utm_source": _u(r["utm_source"]), "utm_campaign": _u(r["utm_campaign"]),
             "utm_medium": _u(r["utm_medium"]), "views": int(r["views"] or 0),
             "visitors": int(r["visitors"] or 0),
             "last_seen": r["last_seen"].isoformat() if r["last_seen"] else None}
            for r in utms
        ],
        "recent": [
            {"created_at": r["created_at"].isoformat() if r["created_at"] else None,
             "page": r["page"], "label": _page_label(r["page"]),
             "country": r["country"], "region": r["region"], "city": r["city"],
             "source": r["source"] or "direct",
             "utm_source": _u(r["utm_source"]), "utm_campaign": _u(r["utm_campaign"]),
             "device": _parse_device(r["user_agent"]),
             "is_online": bool(r["is_online"]),
             "club": ({
                 "id": str(r["club_id"]), "name": r["club_name"],
                 "is_customer": r["club_org_id"] is not None,
             } if r["club_id"] else None)}
            for r in recent
        ],
    }


@router.get("/club-admin/usage/geo")
async def geo(
    hours: int = 24,
    _: User = Depends(require_super_admin),
    db: AsyncSession = Depends(get_db),
):
    """City-level visitor locations for the Usage page's map. Points are city
    centroids from ip-api.com's free geolocation lookup (see
    services/usage_tracker.py) — city/ISP-block precision at best, never a
    street address. Grouped by rounded lat/lng so a city's worth of visitors
    renders as one point rather than a pile of near-duplicates, with
    `is_online` true when any visitor at that point has pinged in the last
    45 seconds (a page_view or a heartbeat — see /usage/heartbeat)."""
    hours = max(1, min(hours, 24 * 30))
    rows = (await db.execute(text(f"""
        SELECT
            round(ue.lat::numeric, 2) AS lat,
            round(ue.lng::numeric, 2) AS lng,
            MAX(ue.city) AS city,
            MAX(ue.region) AS region,
            MAX(ue.country) AS country,
            COUNT(DISTINCT {_VKEY}) AS visitors,
            COUNT(*) FILTER (WHERE ue.event_type = 'page_view') AS views,
            MAX(ue.created_at) AS last_seen,
            BOOL_OR(ue.created_at >= NOW() - INTERVAL '45 seconds') AS is_online
        FROM usage_events ue
        WHERE ue.event_type IN ('page_view', 'heartbeat')
          AND ue.user_id IS NULL
          AND split_part(ue.path, '?', 1) !~* '^/admin'
          AND ue.lat IS NOT NULL AND ue.lng IS NOT NULL
          AND ue.created_at >= NOW() - INTERVAL '{hours} hours'
        GROUP BY 1, 2
        ORDER BY visitors DESC
        LIMIT 500
    """))).mappings().all()

    return {
        "hours": hours,
        "points": [
            {
                "lat": float(r["lat"]), "lng": float(r["lng"]),
                "city": r["city"], "region": r["region"], "country": r["country"],
                "visitors": int(r["visitors"] or 0), "views": int(r["views"] or 0),
                "last_seen": r["last_seen"].isoformat() if r["last_seen"] else None,
                "is_online": bool(r["is_online"]),
            }
            for r in rows
        ],
    }
