"""Shared post-processing for text generated by an LLM call.

Every prompt that generates prose (the yearbook narrative, BetterIQ Ask) also
instructs the model never to use an em/en dash, but that's an instruction,
not a guarantee. Claude reaches for "—" out of habit even when told not to,
a known failure mode (see .claude/skills/humanizer/SKILL.md's own "hard
constraint, not a preference" framing). This is the deterministic backstop,
so a slipped-through dash never reaches a club's page no matter how
reliably the model follows the prompt.
"""
import re

_DASH_RE = re.compile(r"\s*[—–]\s*")  # em dash (U+2014), en dash (U+2013)


def strip_em_dashes(text: str) -> str:
    """Replace any em/en dash with a comma, the humanizer skill's own
    first-choice substitute for a tight aside, and the one substitution safe
    to apply blindly without reparsing sentence structure."""
    if not text:
        return text
    return _DASH_RE.sub(", ", text).strip()
