// Static data tree: category → subcategory → [achievement options]
// Sourced from ACC Honour Boards and Office Bearers spreadsheet

const GRADE_AWARDS = [
  'Best & Fairest',
  'Best Batter',
  'Best Bowler',
  'Batting Aggregate',
  'Batting Average',
  'Bowling Aggregate',
  'Bowling Average',
  'Fielding Award',
  'Player of the Finals',
  'Player of the Grand Final',
  "Coaches Award",
]

const PREMIERSHIP_AWARDS = [
  'Premiership',
  'Player of the Grand Final',
  'Captain',
  '12th Man',
  '13th Man',
]

export const ACHIEVEMENT_TREE = {
  'Club Award': {
    '1st XI': GRADE_AWARDS,
    '2nd XI': GRADE_AWARDS,
    '3rd XI': GRADE_AWARDS,
    '4th XI': GRADE_AWARDS,
    '5th XI': GRADE_AWARDS,
    '6th XI': GRADE_AWARDS,
    'OD1 XI': GRADE_AWARDS,
    'OD2 XI': GRADE_AWARDS,
    'OD3 XI': GRADE_AWARDS,
    'OD4 XI': GRADE_AWARDS,
    'OD5 Black XI': GRADE_AWARDS,
    'OD5 Gold XI': GRADE_AWARDS,
    'T20 Div 1': ['Best & Fairest', 'Best Batter', 'Best Bowler', "Coaches Award"],
    'T20 Div 2': ['Best & Fairest', 'Best Batter', 'Best Bowler', "Coaches Award"],
    'T20 Div 3': ['Best & Fairest', 'Best Batter', 'Best Bowler', "Coaches Award"],
    'ICL A Grade': ['Best & Fairest', 'Best Batter', 'Best Bowler', 'Best Fielder', "Coaches Award"],
    "Women's A Grade": ['Best & Fairest', 'Best Batter', 'Best Bowler', 'Batting Aggregate', 'Batting Average', 'Bowling Aggregate', 'Bowling Average', 'Fielding Award', "Coaches Award"],
    "Women's B Grade": ['Best & Fairest', 'Best Batter', 'Best Bowler', "Coaches Award"],
    'Colts': ['Best & Fairest', 'Best Batter', 'Best Bowler', 'Batting Aggregate', 'Batting Average', 'Bowling Aggregate', 'Bowling Average', 'Fielding Award', "Coaches Award"],
    'Perpetual': [
      "The 'Al Field' Best Clubperson",
      "The 'Russell Kingdon' Presidents Trophy",
      'Best All Round Cricketer',
      'Most Improved',
      'Best Future Prospect',
      "The 'Tom Morgan' Fielding Award",
      "The 'Brett McGregor' Most Determined to Succeed",
      "The 'Rob Wilton' Leading Run Scorer",
      "The 'Ramon Fletcher' Leading Wicket Taker",
      'Season Highest Batting Partnership',
      "The 'Aubrey King' Club Trip Medallion",
      'Roger Weir Memorial Shield - 100 Gamers vs Presidents XI',
      'Wood Duck',
      "Coaches Award",
      'Best 1st Year Player',
      "The 'Greg DeCampo' ICL A Grade Coaches Award",
      'ACC Debut',
    ],
    "Women's Perpetual": [
      'Womens - Best All Round Cricketer',
      'Womens - Best Fielder',
      'Womens - Best Future Prospect',
      "Womens - Coaches Award",
      'Womens - Most Improved',
      'Womens - Season Highest Batting Partnership',
      'Womens - Spirit of Cricket',
    ],
  },
  'Association Award': {
    'WASTCA': [
      // Club
      'Champion Club',
      'Club Championship',
      // Barry Parker
      'Barry Parker Memorial Award',
      'Barry Parker Memorial Award - Best Single Performance in a Match',
      // Spirit
      'Spirit of the Game Award',
      'John Ireland & Paul Pearce Spirit of the Game Award',
      // 1st Grade
      '1st Grade Batting',
      '1st Grade Batting Average',
      '1st Grade Bowling Average',
      '1st Grade Fielding',
      // 2nd Grade
      '2nd Grade Batting Aggregate',
      '2nd Grade Batting Average',
      '2nd Grade Champion Cricketer',
      '2nd Grade Paul Pearce Champion Cricketer',
      '2nd Grade Fielding',
      // 3rd Grade
      '3rd Grade Batting Average',
      '3rd Grade Bowling Aggregate',
      '3rd Grade Bowling Average',
      '3rd Grade Fielding',
      // 4th Grade
      '4th Grade Batting Average',
      '4th Grade Bowling Aggregate',
      '4th Grade Bowling Average',
      '4th Grade Fielding',
      // 5th Grade
      '5th Grade Batting Aggregate',
      '5th Grade Batting Average',
      '5th Grade Bowling',
      '5th Grade Champion Cricketer',
      '5th Grade Fielding',
      // 6th Grade
      '6th Grade Batting Aggregate',
      '6th Grade Batting Average',
      '6th Grade Champion Cricketer',
      // 7th Grade
      '7th Grade Batting Aggregate',
      '7th Grade Batting Average',
      '7th Grade Bowling Average',
      '7th Grade Fielding',
      // 8th Grade
      '8th Grade Batting Aggregate',
      '8th Grade Batting Average',
      '8th Grade Bowling Aggregate',
      '8th Grade Bowling Average',
      // 9th Grade
      '9th Grade Batting',
      '9th Grade Bowling',
      '9th Grade Fielding',
      // 10th Grade
      '10th Grade Batting',
      '10th Grade Bowling Average',
      // One Day
      'OD2 Batting Aggregate',
      'OD2 Bowling Average',
      'OD2 Fielding',
      'OD4 Batting Average',
      'OD4 Champion Player',
      'OD5 Champion Cricketer',
      'OD5 Bowling Aggregate',
      'OD5 Black Champion Cricketer',
      'OD5 Black Bowling Aggregate',
      'One Day Division 1 Bowling Average',
      'One Day Div 2 Bowling Aggregate',
      'One Day Div 3 Bowling Aggregate',
      // Colts
      'Colts Batting',
      'Colts Spirit of the Game Award',
    ],
    'WABCC': [
      'Batting Award',
      'Bowling Award',
      'Fielding Award',
      'Most Improved',
      'Best New Player',
      'Best Team Player',
      "Coach's Award",
      "Captain's Award",
      'Volunteer Award',
      'Les Buchanan Medal',
    ],
    'PSWL': [
      // Metro
      'PSWL Metro: Champion Player',
      'PSWL Metro: Batting Average',
      'PSWL Metro: Batting Aggregate (Runner Up)',
      'PSWL Metro: Bowling Aggregate',
      'PSWL Metro: Bowling Average (Runner Up)',
      // South A
      'PSWL South A - Batting Average',
      'PSWL South A - Bowling Aggregate Runner Up',
      'PSWL South A - Bowling Average Runner Up',
      // South B
      'PSWL South B - Spirit of Cricket',
      // General
      'PSWL South Premiership',
      'PSWL South Conference Runner Up Bowling Aggregate',
    ],
    'ACC': [
      'Hall of Fame',
      'WACA Inclusion and Diversity Award',
    ],
  },
  'Office Bearer': {
    'Executive Committee': [
      'President',
      'Vice President',
      "Vice President - Men's Cricket",
      "Vice President - Women's Cricket",
      "Vice President - Junior Cricket",
      'Treasurer',
      'Secretary',
      'Operations',
    ],
    'General Committee': [
      'Committee',
      'Junior Committee',
    ],
    'Captains': [
      '1st XI Captain',
      '2nd XI Captain',
      '3rd XI Captain',
      '4th XI Captain',
      '5th XI Captain',
      '6th XI Captain',
      'OD1 XI Captain',
      'OD2 XI Captain',
      'OD3 XI Captain',
      'OD4 XI Captain',
      'OD5 Black XI Captain',
      'OD5 XI Captain',
      'OD5 Gold XI Captain',
      'T20 Div 1 Captain',
      'T20 Div 2 Captain',
      'T20 Div 3 Captain',
      'Colts Captain',
      'ICL A Grade Captain',
      "Women's A Captain",
      "Women's B Captain",
    ],
    'Coaches': [
      'Club Coach',
      'Head Coach',
      'Assistant Coach',
      'Director of Cricket',
      "Women's Coach",
      "Women's Cricket Coordinator",
      'Nets Coach',
      'Nets Coordinator',
      'Colts Coach',
      'Junior Coordinator',
    ],
    'Other Roles': [
      'Chairman of Selectors',
      'SSRSA Representative',
      'WASTCA Delegate',
      'WASTCA Director',
      'Grounds Officer',
      'Curator',
      'Turf Curator',
      'Bar Manager',
      'Sponsorship Manager',
      'Social Media Manager',
      'Registrar',
      'Match Day Coordinator',
    ],
  },
  'Premiership': {
    '1st XI': PREMIERSHIP_AWARDS,
    '2nd XI': PREMIERSHIP_AWARDS,
    '3rd XI': PREMIERSHIP_AWARDS,
    '4th XI': PREMIERSHIP_AWARDS,
    '5th XI': PREMIERSHIP_AWARDS,
    '6th XI': PREMIERSHIP_AWARDS,
    'OD1 XI': PREMIERSHIP_AWARDS,
    'OD2 XI': PREMIERSHIP_AWARDS,
    'OD3 XI': PREMIERSHIP_AWARDS,
    'OD4 XI': PREMIERSHIP_AWARDS,
    'OD5 Black XI': PREMIERSHIP_AWARDS,
    'OD5 Gold XI': PREMIERSHIP_AWARDS,
    'OD5 XI': PREMIERSHIP_AWARDS,
    'T20 Div 1': ['Premiership', 'Player of the Grand Final', 'Captain'],
    'T20 Div 2': ['Premiership', 'Player of the Grand Final', 'Captain'],
    'T20 Div 3': ['Premiership', 'Player of the Grand Final', 'Captain'],
    'ICL A Grade': ['Premiership', 'Player of the Grand Final', 'Captain'],
    "Women's A Grade": ['Premiership', 'Player of the Grand Final', 'Captain'],
    "Women's B Grade": ['Premiership', 'Player of the Grand Final', 'Captain'],
    'Colts': ['Premiership', 'Player of the Grand Final', 'Captain'],
  },
  'Hall of Fame': {
    'ACC': ['Hall of Fame'],
  },
  'Life Membership': {
    'ACC': ['Life Membership'],
  },
  'Milestone': {
    'Cap Number': ['Player Number', '100 Game Number', '200 Game Number', '300 Game Number', '400 Game Number', '500 Game Number', '600 Game Number', '700 Game Number', '800 Game Number', '900 Game Number', '1000 Game Number'],
    'Games': ['50 Games', '100 Games', '150 Games', '200 Games', '250 Games', '300 Games', '350 Games', '400 Games', '450 Games', '500 Games'],
    'Runs': ['500 Runs', '1000 Runs', '2000 Runs', '3000 Runs', '4000 Runs', '5000 Runs', '6000 Runs', '7000 Runs', '8000 Runs', '9000 Runs', '10000 Runs'],
    'Wickets': ['50 Wickets', '100 Wickets', '150 Wickets', '200 Wickets', '250 Wickets', '300 Wickets', '350 Wickets', '400 Wickets', '450 Wickets', '500 Wickets', '550 Wickets', '600 Wickets', '650 Wickets', '700 Wickets'],
    'Catches': ['50 Catches', '100 Catches', '150 Catches', '200 Catches', '250 Catches', '300 Catches'],
    'Hat Tricks': ['Hat Trick'],
    'Individual Score': ['50', '100', '150', '200'],
    'Bowling': ['5 Wickets in an Innings', '10 Wickets in a Match'],
  },
}

// Flat list of all subcategories per category
export function getSubcategories(category) {
  return Object.keys(ACHIEVEMENT_TREE[category] || {})
}

// Flat list of all achievement options for category+subcategory
export function getAchievements(category, subcategory) {
  return (ACHIEVEMENT_TREE[category] || {})[subcategory] || []
}
