// Static data tree: category → subcategory → [achievement options]
// Sourced from ACC Honour Boards and Office Bearers spreadsheet

const GRADE_AWARDS = [
  'Best & Fairest',
  'Best Batter',
  'Best Bowler',
  'Batting Aggregate',
  'Batting Average',
  'Bowling Aggregate',
  'Bowling Average',
  'Fielding Award',
  'Player of the Finals',
  'Player of the Grand Final',
  "Coaches Award",
]

const PREMIERSHIP_AWARDS = [
  'Premiership',
  'Player of the Grand Final',
  'Captain',
  '12th Man',
  '13th Man',
]

export const ACHIEVEMENT_TREE = {
  'Club Award': {
    '1st XI': GRADE_AWARDS,
    '2nd XI': GRADE_AWARDS,
    '3rd XI': GRADE_AWARDS,
    '4th XI': GRADE_AWARDS,
    '5th XI': GRADE_AWARDS,
    '6th XI': GRADE_AWARDS,
    'OD1 XI': GRADE_AWARDS,
    'OD2 XI': GRADE_AWARDS,
    'OD3 XI': GRADE_AWARDS,
    'OD4 XI': GRADE_AWARDS,
    'OD5 Black XI': GRADE_AWARDS,
    'OD5 Gold XI': GRADE_AWARDS,
    'T20 Div 1': ['Best & Fairest', 'Best Batter', 'Best Bowler', "Coaches Award"],
    'T20 Div 2': ['Best & Fairest', 'Best Batter', 'Best Bowler', "Coaches Award"],
    'T20 Div 3': ['Best & Fairest', 'Best Batter', 'Best Bowler', "Coaches Award"],
    'ICL A Grade': ['Best & Fairest', 'Best Batter', 'Best Bowler', 'Best Fielder', "Coaches Award"],
    "Women's A Grade": ['Best & Fairest', 'Best Batter', 'Best Bowler', 'Batting Aggregate', 'Batting Average', 'Bowling Aggregate', 'Bowling Average', 'Fielding Award', "Coaches Award"],
    "Women's B Grade": ['Best & Fairest', 'Best Batter', 'Best Bowler', "Coaches Award"],
    'Colts': ['Best & Fairest', 'Best Batter', 'Best Bowler', 'Batting Aggregate', 'Batting Average', 'Bowling Aggregate', 'Bowling Average', 'Fielding Award', "Coaches Award"],
    'Perpetual': [
      "The 'Al Field' Best Clubperson",
      "The 'Russell Kingdon' Presidents Trophy",
      'Best All Round Cricketer',
      'Most Improved',
      'Best Future Prospect',
      "The 'Tom Morgan' Fielding Award",
      "The 'Brett McGregor' Most Determined to Succeed",
      "The 'Rob Wilton' Leading Run Scorer",
      "The 'Ramon Fletcher' Leading Wicket Taker",
      'Season Highest Batting Partnership',
      "The 'Aubrey King' Club Trip Medallion",
      'Roger Weir Memorial Shield - 100 Gamers vs Presidents XI',
      'Wood Duck',
      "Coaches Award",
      'Best 1st Year Player',
      "The 'Greg DeCampo' ICL A Grade Coaches Award",
      'ACC Debut',
    ],
    "Women's Perpetual": [
      'Womens - Best All Round Cricketer',
      'Womens - Best Fielder',
      'Womens - Best Future Prospect',
      "Womens - Coaches Award",
      'Womens - Most Improved',
      'Womens - Season Highest Batting Partnership',
      'Womens - Spirit of Cricket',
    ],
  },
  'Association Award': {
    'WASTCA': [
      'Champion Club',
      '3rd Grade Batting Aggregate',
      '3rd Grade Batting Average',
      '3rd Grade Bowling Aggregate',
      '3rd Grade Bowling Average',
      'OD4 Batting Aggregate',
      'OD4 Batting Average',
      'OD4 Bowling Aggregate',
      'OD4 Bowling Average',
      'OD5 Champion Cricketer',
      'OD5 Batting Aggregate',
      'OD5 Batting Average',
      'OD5 Bowling Aggregate',
      'OD5 Bowling Average',
      'Barry Parker Memorial Award',
      'Noel Sherwood Medal',
      'Club Volunteer Award',
      'Rising Star',
    ],
    'WABCC': [
      'Batting Award',
      'Bowling Award',
      'Fielding Award',
      'Most Improved',
      'Best New Player',
      'Best Team Player',
      "Coach's Award",
      "Captain's Award",
      'Volunteer Award',
      'Les Buchanan Medal',
    ],
    'PSWL': [
      'Champion Player',
      'South A Batting Average',
      'South A Batting Aggregate',
      'South A Bowling Aggregate',
      'South A Bowling Average',
      'South A Bowling Average (Runner Up)',
      'South B Batting Average',
      'South B Batting Aggregate',
      'South B Bowling Aggregate',
      'South B Bowling Average',
      'South B Spirit of Cricket',
      'Spirit of Cricket',
    ],
    'ACC': [
      'Hall of Fame',
    ],
  },
  'Office Bearer': {
    'Executive Committee': [
      'President',
      'Vice President',
      "Vice President - Men's Cricket",
      "Vice President - Women's Cricket",
      "Vice President - Junior Cricket",
      'Treasurer',
      'Secretary',
      'Operations',
    ],
    'General Committee': [
      'Committee',
      'Junior Committee',
    ],
    'Captains': [
      '1st XI Captain',
      '2nd XI Captain',
      '3rd XI Captain',
      '4th XI Captain',
      '5th XI Captain',
      '6th XI Captain',
      'OD1 XI Captain',
      'OD2 XI Captain',
      'OD3 XI Captain',
      'OD4 XI Captain',
      'OD5 Black XI Captain',
      'OD5 XI Captain',
      'OD5 Gold XI Captain',
      'T20 Div 1 Captain',
      'T20 Div 2 Captain',
      'T20 Div 3 Captain',
      'Colts Captain',
      'ICL A Grade Captain',
      "Women's A Captain",
      "Women's B Captain",
    ],
    'Coaches': [
      'Club Coach',
      'Head Coach',
      'Assistant Coach',
      'Director of Cricket',
      "Women's Coach",
      "Women's Cricket Coordinator",
      'Nets Coach',
      'Nets Coordinator',
      'Colts Coach',
      'Junior Coordinator',
    ],
    'Other Roles': [
      'Chairman of Selectors',
      'SSRSA Representative',
      'WASTCA Delegate',
      'WASTCA Director',
      'Grounds Officer',
      'Curator',
      'Turf Curator',
      'Bar Manager',
      'Sponsorship Manager',
      'Social Media Manager',
      'Registrar',
      'Match Day Coordinator',
    ],
  },
  'Premiership': {
    '1st XI': PREMIERSHIP_AWARDS,
    '2nd XI': PREMIERSHIP_AWARDS,
    '3rd XI': PREMIERSHIP_AWARDS,
    '4th XI': PREMIERSHIP_AWARDS,
    '5th XI': PREMIERSHIP_AWARDS,
    '6th XI': PREMIERSHIP_AWARDS,
    'OD1 XI': PREMIERSHIP_AWARDS,
    'OD2 XI': PREMIERSHIP_AWARDS,
    'OD3 XI': PREMIERSHIP_AWARDS,
    'OD4 XI': PREMIERSHIP_AWARDS,
    'OD5 Black XI': PREMIERSHIP_AWARDS,
    'OD5 Gold XI': PREMIERSHIP_AWARDS,
    'OD5 XI': PREMIERSHIP_AWARDS,
    'T20 Div 1': ['Premiership', 'Player of the Grand Final', 'Captain'],
    'T20 Div 2': ['Premiership', 'Player of the Grand Final', 'Captain'],
    'T20 Div 3': ['Premiership', 'Player of the Grand Final', 'Captain'],
    'ICL A Grade': ['Premiership', 'Player of the Grand Final', 'Captain'],
    "Women's A Grade": ['Premiership', 'Player of the Grand Final', 'Captain'],
    "Women's B Grade": ['Premiership', 'Player of the Grand Final', 'Captain'],
    'Colts': ['Premiership', 'Player of the Grand Final', 'Captain'],
  },
  'Hall of Fame': {
    'ACC': ['Hall of Fame'],
  },
  'Life Membership': {
    'ACC': ['Life Membership'],
  },
  'Milestone': {
    'Games': ['50 Games', '100 Games', '150 Games', '200 Games', '250 Games', '300 Games', '350 Games', '400 Games', '450 Games', '500 Games'],
    'Runs': ['500 Runs', '1000 Runs', '2000 Runs', '3000 Runs', '4000 Runs', '5000 Runs', '6000 Runs', '7000 Runs', '8000 Runs', '9000 Runs', '10000 Runs'],
    'Wickets': ['50 Wickets', '100 Wickets', '150 Wickets', '200 Wickets', '250 Wickets', '300 Wickets', '350 Wickets', '400 Wickets', '450 Wickets', '500 Wickets', '550 Wickets', '600 Wickets', '650 Wickets', '700 Wickets'],
    'Catches': ['50 Catches', '100 Catches', '150 Catches', '200 Catches', '250 Catches', '300 Catches'],
    'Hat Tricks': ['Hat Trick'],
    'Individual Score': ['50', '100', '150', '200'],
    'Bowling': ['5 Wickets in an Innings', '10 Wickets in a Match'],
  },
}

// Flat list of all subcategories per category
export function getSubcategories(category) {
  return Object.keys(ACHIEVEMENT_TREE[category] || {})
}

// Flat list of all achievement options for category+subcategory
export function getAchievements(category, subcategory) {
  return (ACHIEVEMENT_TREE[category] || {})[subcategory] || []
}
