// Capability constants — keep in sync with backend/app/auth/capabilities.py

export const CAP = {
  MANAGE_SETTINGS: 'manage_settings',
  MANAGE_PLAYERS: 'manage_players',
  MANAGE_MERGES: 'manage_merges',
  MANAGE_YEARBOOKS: 'manage_yearbooks',
  MANAGE_AWARDS: 'manage_awards',
  MANAGE_SPONSORS: 'manage_sponsors',
  MANAGE_WEBSITE: 'manage_website',
  MANAGE_SOCIAL: 'manage_social',
  MANAGE_MILESTONES: 'manage_milestones',
  RUN_SYNC: 'run_sync',
  RUN_HARD_REFRESH: 'run_hard_refresh',
  MANAGE_USERS: 'manage_users',
  MANAGE_REPORTS: 'manage_reports',
  MANAGE_FAMILIES: 'manage_families',
  MANAGE_MANUAL_ENTRIES: 'manage_manual_entries',
  MANAGE_FEES: 'manage_fees',
  MANAGE_FIXTURES: 'manage_fixtures',
  MANAGE_SELECTIONS: 'manage_selections',
  MANAGE_IQ: 'manage_iq',
  MANAGE_COMMS: 'manage_comms',
  MANAGE_MERCH: 'manage_merch',
  MANAGE_FANTASY: 'manage_fantasy',
  MANAGE_CRM: 'manage_crm',
  MANAGE_COMMITTEE: 'manage_committee',
  MANAGE_VOLUNTEERS: 'manage_volunteers',
  MANAGE_QUALIFICATIONS: 'manage_qualifications',
  MANAGE_ASSETS: 'manage_assets',
}

// Display metadata for the user-management UI checkboxes.
export const CAPABILITY_INFO = [
  { key: CAP.MANAGE_SETTINGS, label: 'Manage settings', hint: 'Club name, colours, logo' },
  { key: CAP.MANAGE_PLAYERS, label: 'Manage players', hint: 'Edit player profiles + photos' },
  { key: CAP.MANAGE_MERGES, label: 'Merge data', hint: 'Merge players, grades and seasons' },
  { key: CAP.MANAGE_YEARBOOKS, label: 'Manage yearbooks', hint: 'Yearbooks, sections, honour board' },
  { key: CAP.MANAGE_AWARDS, label: 'Manage awards', hint: 'Awards + achievements + award types' },
  { key: CAP.MANAGE_SPONSORS, label: 'Manage sponsors', hint: 'Sponsor list + logos' },
  { key: CAP.MANAGE_WEBSITE, label: 'Manage website', hint: 'Public club website: news, pages, honours, committee, galleries' },
  { key: CAP.MANAGE_SOCIAL, label: 'Manage social posts', hint: 'Social Post tool' },
  { key: CAP.MANAGE_MILESTONES, label: 'Manage milestones', hint: 'Milestone definitions + manual entry' },
  { key: CAP.RUN_SYNC, label: 'Run data sync', hint: 'Sync Now + Fix Missing Totals' },
  { key: CAP.RUN_HARD_REFRESH, label: 'Run hard refresh', hint: 'Destructive — wipes + re-syncs everything (1h+)' },
  { key: CAP.MANAGE_USERS, label: 'Manage users', hint: 'Invite club members + assign capabilities' },
  { key: CAP.MANAGE_REPORTS, label: 'Manage saved reports', hint: 'Approve / reject saved StatLab reports' },
  { key: CAP.MANAGE_FAMILIES, label: 'Manage families', hint: 'Create and edit player family groupings' },
  { key: CAP.MANAGE_MANUAL_ENTRIES, label: 'Manual stat entry', hint: 'Add historical games + season/career adjustments. Reversible via audit log.' },
  { key: CAP.MANAGE_FEES, label: 'Manage fees', hint: 'Membership tiers, members + match-day fee tracking' },
  { key: CAP.MANAGE_FIXTURES, label: 'Manage fixtures', hint: 'BetterSelect: sync + manually add upcoming fixtures' },
  { key: CAP.MANAGE_SELECTIONS, label: 'Manage selections', hint: 'BetterSelect: teams, availability and team selection' },
  { key: CAP.MANAGE_IQ, label: 'Manage BetterIQ', hint: 'BetterIQ: opposition scouting + analytics' },
  { key: CAP.MANAGE_COMMS, label: 'Manage BetterComms', hint: 'BetterComms: contacts + bulk email campaigns' },
  { key: CAP.MANAGE_MERCH, label: 'Manage BetterMerch', hint: 'BetterMerch: club stock — apparel, equipment and canteen' },
  { key: CAP.MANAGE_FANTASY, label: 'Manage BetterFantasyCricket', hint: 'BetterFantasyCricket: fantasy season setup, leagues and round settlement' },
  { key: CAP.MANAGE_CRM, label: 'Manage BetterCRM', hint: 'BetterCRM: contacts, deals/pipeline and activities' },
  { key: CAP.MANAGE_COMMITTEE, label: 'Manage committee', hint: 'Positions, terms, task register, documents, club calendar' },
  { key: CAP.MANAGE_VOLUNTEERS, label: 'Manage volunteers', hint: 'Volunteer profiles and hours ledger' },
  { key: CAP.MANAGE_QUALIFICATIONS, label: 'Manage qualifications', hint: 'Accreditations, WWCC, First Aid — with expiry tracking' },
  { key: CAP.MANAGE_ASSETS, label: 'Manage assets & facilities', hint: 'Club property, grounds/clubhouse bookings, maintenance logs' },
]
